(function (root) {
  'use strict';
  const engine = root.CRS_ENGINE;
  if (!engine) return;
  const {registry, byId, transform} = engine;
  const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const format = (number, digits = 2) => new Intl.NumberFormat('ro-RO', {minimumFractionDigits:digits,maximumFractionDigits:digits}).format(number);
  const options = selected => registry.crs.map(c => `<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.short_name)} · ${c.id}</option>`).join('');
  const external = (url, label) => `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(label)}; se deschide într-o filă nouă">${esc(label)} ↗</a>`;
  const isPulkovo = id => byId[id].datum === 'Pulkovo 1942(58)';
  const datumNote = (a,b) => isPulkovo(a)!==isPulkovo(b) ? 'Transformarea Pulkovo 1942(58) ↔ WGS 84 folosește EPSG:15995, cu precizie declarată de ordinul a 3 metri. Rezultatul este destinat explorării didactice.' : (a==='EPSG:3035'||b==='EPSG:3035') ? 'WGS 84 și ETRS89 sunt tratate ca aproximativ coincidente; nu se aplică o transformare dependentă de epocă.' : '';

  function card(crs) {
    return `<article class="crs-card" data-filterable data-content-type="concept,qgis" data-level="detailed" data-source="modern" data-theme="coordonate"><div class="crs-card-head"><h3>${esc(crs.short_name)}</h3><span class="meta-chip">${crs.id}</span></div><p class="crs-official">${esc(crs.name)}</p><dl><div><dt>Tip</dt><dd>${esc(crs.type)}</dd></div><div><dt>Datum / bază</dt><dd>${esc(crs.datum)}</dd></div>${crs.projection_method?`<div><dt>Proiecție</dt><dd>${esc(crs.projection_method)}</dd></div>`:''}<div><dt>Unități</dt><dd>${esc(crs.units)}</dd></div><div><dt>Arie</dt><dd>${esc(crs.area_of_use)}</dd></div><div><dt>Utilizare</dt><dd>${esc(crs.typical_use)}</dd></div><div><dt>Ordine EPSG</dt><dd>${esc(crs.axis_order)}</dd></div><div><dt>În acest site</dt><dd>${esc(crs.display_axes)}</dd></div></dl>${external(crs.source_url,`Fișa oficială ${crs.id}`)}</article>`;
  }
  function render(lesson, helpers) {
    const rootEl = document.querySelector('#lesson-root');
    rootEl.innerHTML = helpers.lessonIntro(lesson,'De la un punct pe Pământ la valori X/Y în metri: explorează grila, compară sisteme de referință și transformă coordonate local, în browser.')+
      `<nav class="lesson-jump"><a href="#concept-rect">Concept</a><a href="#grila">Grilă</a><a href="#comparatie">Comparație</a><a href="#catalog-crs">Catalog CRS</a><a href="#zone-ro">Zone România</a><a href="#transformare">Transformă</a></nav>
      <section id="concept-rect" class="lesson-section"><span class="eyebrow">1.2 / CONCEPT</span><h2>Ce sunt coordonatele rectangulare?</h2><p>O grilă carteziană are două axe perpendiculare și o origine. Poziția unui punct este dată de două distanțe măsurate de la origine. Într-un CRS proiectat, aceste valori sunt de regulă în metri: <strong>Easting</strong> spre est și <strong>Northing</strong> spre nord. Originea și deplasările convenționale (<em>false easting</em>, <em>false northing</em>) pot face valorile pozitive într-o zonă de lucru.</p><div class="crs-compare"><article><h3>Coordonate geografice</h3><p>Latitudine / longitudine</p><strong>Unghiuri · grade</strong><small>WGS 84, EPSG:4326. Acesta este un CRS geografic, nu o proiecție cartografică.</small></article><article><h3>Coordonate rectangulare</h3><p>X/Y ori Easting/Northing</p><strong>Distanțe pe grila proiectată · metri</strong><small>Un CRS proiectat include datum, metodă, parametri, unități și axe. Codul EPSG identifică întregul CRS.</small></article></div><p class="small">Ordinea oficială a axelor diferă între sisteme și formate. Pentru introducere și afișare, acest site folosește mereu perechea <strong>est, nord</strong> (sau <strong>longitudine, latitudine</strong> pentru EPSG:4326); fiecare fișă arată separat ordinea formală EPSG.</p><p><a href="coordinates.html">Înapoi la 1.1 Coordonatele geografice →</a> · <a href="lesson.html?id=projection-basics">Proiecții — principii →</a></p></section>
      <section id="grila" class="lesson-section"><span class="eyebrow">EXPERIMENT INTERACTIV</span><h2>Grilă metrică, același punct</h2><div class="crs-controls"><label>Localitate de referință<select id="crs-location">${registry.locations.map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></label><label>Sistem de coordonate / CRS<select id="grid-crs">${options('EPSG:3844')}</select></label></div><p id="location-source" class="small"></p><div class="crs-grid-layout"><svg id="metric-grid" viewBox="0 0 640 450" role="img" aria-label="Grilă de coordonate a punctului ales"></svg><div id="grid-meta" class="crs-grid-meta" aria-live="polite"></div></div></section>
      <section id="comparatie" class="lesson-section"><span class="eyebrow">COMPARAȚIE SINCRONIZATĂ</span><h2>Același punct, coordonate diferite</h2><p>Valorile de mai jos sunt calculate din aceeași poziție WGS 84 selectată deasupra.</p><div id="crs-comparison" class="crs-comparison"></div></section>
      <section id="catalog-crs" class="lesson-section"><span class="eyebrow">CRS ÎN PRACTICĂ</span><h2>Catalogul celor opt sisteme</h2><p>Proiecțiile din capitolul istoric descriu principii geometrice. Fișele de aici sunt sisteme operaționale care adaugă datum, parametri, unități, arie de utilizare și identificator EPSG.</p><div class="crs-catalog">${registry.crs.map(card).join('')}</div></section>
      <section id="zone-ro" class="lesson-section"><span class="eyebrow">SCHEMĂ EXPLICATIVĂ</span><h2>Zonele României la meridianul 24°E</h2><p>UTM 34N și Gauss–Krüger 4 acoperă banda 18°–24°E; UTM 35N și Gauss–Krüger 5 banda 24°–30°E. Zonele se întind și în afara conturului României.</p><div class="zone-map"><svg viewBox="0 0 600 275" role="img" aria-label="Schemă a României împărțită la meridianul 24 grade est"><defs><clipPath id="romania-outline"><path d="M94 96 L143 75 L187 81 L220 61 L255 76 L296 65 L331 84 L375 72 L413 94 L452 89 L483 113 L493 145 L469 165 L440 174 L438 205 L395 211 L359 195 L315 208 L276 193 L249 210 L215 198 L179 207 L157 183 L128 180 L103 151 L82 130 Z"/></clipPath></defs><rect x="54" y="35" width="246" height="204" class="zone-west"/><rect x="300" y="35" width="246" height="204" class="zone-east"/><g clip-path="url(#romania-outline)"><rect x="54" y="35" width="246" height="204" class="zone-west-fill"/><rect x="300" y="35" width="246" height="204" class="zone-east-fill"/></g><path d="M94 96 L143 75 L187 81 L220 61 L255 76 L296 65 L331 84 L375 72 L413 94 L452 89 L483 113 L493 145 L469 165 L440 174 L438 205 L395 211 L359 195 L315 208 L276 193 L249 210 L215 198 L179 207 L157 183 L128 180 L103 151 L82 130 Z" class="zone-outline"/><path d="M300 35V239" class="zone-boundary"/><text x="68" y="258">18°E</text><text x="285" y="258">24°E</text><text x="515" y="258">30°E</text><text x="111" y="23">Vest · 34N / GK4</text><text x="350" y="23">Est · 35N / GK5</text></svg><div class="zone-actions"><button type="button" data-zone="EPSG:32634">UTM 34N</button><button type="button" data-zone="EPSG:32635">UTM 35N</button><button type="button" data-zone="EPSG:3334">Gauss–Krüger 4</button><button type="button" data-zone="EPSG:3335">Gauss–Krüger 5</button></div><p id="zone-description" aria-live="polite">Alege o zonă pentru a o evidenția și a o afișa în grilă.</p></div></section>
      <section id="transformare" class="lesson-section"><span class="eyebrow">LABORATOR</span><h2>Transformă coordonate</h2><p>Introdu valori în ordinea de afișare <strong>est, nord</strong> sau <strong>longitudine, latitudine</strong>. Selectează orice pereche din catalog; calculul folosește Proj4js local.</p><form id="transform-form" class="transform-layout"><div class="transform-side"><h3>Intrare</h3><label>CRS de intrare<select id="input-crs">${options('EPSG:3844')}</select></label><label id="input-x-label">Easting / X<input id="input-x" type="text" inputmode="decimal" required></label><label id="input-y-label">Northing / Y<input id="input-y" type="text" inputmode="decimal" required></label><button class="outline-button" type="button" id="fill-example">Folosește punctul ales</button></div><div class="transform-arrow" aria-hidden="true">→</div><div class="transform-side"><h3>Ieșire</h3><label>CRS de ieșire<select id="output-crs">${options('EPSG:4326')}</select></label><button class="primary-button" type="submit">Transformă →</button><div id="transform-result" class="transform-result" role="status" aria-live="polite">Introdu coordonatele și apasă Transformă.</div></div></form><p class="small">Valorile afișate sunt pentru explorare didactică. Pentru utilizări inginerești, verifică operația disponibilă și precizia cerută în software GIS.</p></section>
      <section class="lesson-section"><article class="layer-card gis-card" data-filterable data-content-type="qgis" data-level="detailed" data-source="gis" data-theme="coordonate"><span class="source-tag qgis-tag">Corespondență GIS modernă · QGIS 3.44</span><h3>De la CRS-ul proiectului la date transformate</h3><p>În QGIS, CRS-ul proiectului controlează afișarea; un strat poate avea alt CRS și este reproiectat pe loc. Pentru a salva efectiv un nou set de date într-un alt CRS, folosește exportul stratului cu CRS-ul țintă.</p>${external('https://docs.qgis.org/3.44/en/docs/training_manual/vector_analysis/reproject_transform.html','Vezi în QGIS: Reprojecting and Transforming Data')}</article></section>` + helpers.lessonTail(lesson);
    init();
  }

  function init() {
    const $ = s => document.querySelector(s);
    const locationSelect = $('#crs-location'), gridSelect = $('#grid-crs');
    const location = () => registry.locations.find(l=>l.id===locationSelect.value);
    const current = () => [location().lon,location().lat];
    function draw() {
      const loc=location(), c=byId[gridSelect.value], [x,y]=transform('EPSG:4326',c.id,current());
      $('#location-source').innerHTML=`${esc(loc.name)}: ${format(loc.lat,5)}° N, ${format(loc.lon,5)}° E · punct reprezentativ de localitate, <a href="${esc(loc.source_url)}" target="_blank" rel="noopener noreferrer">GeoNames ↗</a>. Nu este reper geodezic.`;
      const step=c.units==='grade'?0.05:10000, ox=320, oy=215, gap=70;
      let lines=''; for(let i=-4;i<=4;i++){const pos=ox+i*gap, value=x+i*step;lines+=`<line x1="${pos}" y1="22" x2="${pos}" y2="405"/><text x="${pos+3}" y="426">${format(value,c.units==='grade'?2:0)}</text>`;}
      for(let i=-2;i<=2;i++){const pos=oy-i*gap, value=y+i*step;lines+=`<line x1="68" y1="${pos}" x2="600" y2="${pos}"/><text x="4" y="${pos-4}">${format(value,c.units==='grade'?2:0)}</text>`;}
      $('#metric-grid').innerHTML=`<g class="grid-lines">${lines}</g><path class="grid-x-axis" d="M68 ${oy}H600"/><path class="grid-y-axis" d="M${ox} 22V405"/><circle class="grid-point" cx="${ox}" cy="${oy}" r="9"/><text class="grid-point-label" x="${ox+14}" y="${oy-15}">${esc(loc.name)}</text><text class="grid-axis-label" x="570" y="${oy-10}">${c.units==='grade'?'Lon':'E'}</text><text class="grid-axis-label" x="${ox+12}" y="39">${c.units==='grade'?'Lat':'N'}</text>`;
      const digits=c.units==='grade'?5:(isPulkovo(c.id)?0:2);
      $('#grid-meta').innerHTML=`<span class="source-tag interactive-tag">Punct fix · valori recalculate</span><h3>${esc(c.short_name)}</h3><p><strong>${c.id}</strong> · ${esc(c.type)}</p><p>Datum: ${esc(c.datum)}</p><p>Unitate: ${esc(c.units)}</p><p>Ordine EPSG: ${esc(c.axis_order)}</p><p>Afișare aici: ${esc(c.display_axes)}</p><div class="grid-values"><strong>${c.units==='grade'?'Lon':'Est'} ${format(x,digits)} ${c.units==='grade'?'°':'m'}</strong><strong>${c.units==='grade'?'Lat':'Nord'} ${format(y,digits)} ${c.units==='grade'?'°':'m'}</strong></div><p class="small">${esc(datumNote('EPSG:4326',c.id))}</p>`;
      const ids=['EPSG:4326','EPSG:3844',loc.lon<24?'EPSG:32634':'EPSG:32635','EPSG:3857'];
      $('#crs-comparison').innerHTML=ids.map(id=>{const cr=byId[id],v=transform('EPSG:4326',id,current()),d=cr.units==='grade'?5:(isPulkovo(id)?0:2);return `<article><span>${cr.id}</span><h3>${esc(cr.short_name)}</h3><strong>${format(v[0],d)} ${cr.units==='grade'?'°':'m'}</strong><strong>${format(v[1],d)} ${cr.units==='grade'?'°':'m'}</strong><small>${esc(cr.display_axes)}</small></article>`;}).join('');
    }
    locationSelect.addEventListener('change',draw); gridSelect.addEventListener('change',draw);
    document.querySelectorAll('[data-zone]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-zone]').forEach(b=>b.classList.toggle('active',b===button));gridSelect.value=button.dataset.zone;draw();$('#zone-description').textContent=`${byId[button.dataset.zone].name}: ${byId[button.dataset.zone].romanian_context}. Meridian central ${byId[button.dataset.zone].central_meridian}°E.`;}));
    function setInputLabels(){const geo=$('#input-crs').value==='EPSG:4326';$('#input-x-label').firstChild.textContent=geo?'Longitudine (grade)':'Est / prima valoare (metri)';$('#input-y-label').firstChild.textContent=geo?'Latitudine (grade)':'Nord / a doua valoare (metri)';}
    $('#input-crs').addEventListener('change',setInputLabels);
    $('#fill-example').addEventListener('click',()=>{const v=transform('EPSG:4326',$('#input-crs').value,current());$('#input-x').value=v[0].toFixed(5);$('#input-y').value=v[1].toFixed(5);$('#transform-form').requestSubmit();});
    $('#transform-form').addEventListener('submit',event=>{event.preventDefault();const source=$('#input-crs').value,target=$('#output-crs').value;try{const x=Number($('#input-x').value.trim().replace(',','.')),y=Number($('#input-y').value.trim().replace(',','.'));if(!$('#input-x').value.trim()||!$('#input-y').value.trim())throw new Error('Introduceți ambele coordonate.');const v=transform(source,target,[x,y]),c=byId[target],d=c.units==='grade'?5:(isPulkovo(source)!==isPulkovo(target)?0:2);$('#transform-result').innerHTML=`<strong>${esc(c.short_name)} · ${target}</strong><span>${format(v[0],d)} ${c.units==='grade'?'°':'m'}</span><span>${format(v[1],d)} ${c.units==='grade'?'°':'m'}</span><small>Ordine afișată: ${esc(c.display_axes)}</small><small>${esc(datumNote(source,target))}</small>`;}catch(error){$('#transform-result').textContent=error.message;}});
    setInputLabels();draw();$('#fill-example').click();
  }
  root.CRS_LESSON={render};
})(window);
