/* Original diagrams on the shared lab shell, controls, state and source cards. */
(function(root){
  'use strict';const F=root.CARTO_FORMATS,M=root.CARTO_FORMATS_MODEL,L=root.CARTO_LAB,{esc}=L;
  const formatOptions=ids=>ids.map(id=>[id,F.byId[id].name]),subsetOptions=Object.entries(F.subsets).map(([id,v])=>[id,v.label]),times=Array.from({length:6},(_,i)=>[String(i),'t'+(i+1)]);
  const select=(key,label,value,options,when)=>({type:'select',key,label,value,options,...(when?{when}:{})}),base={source:'formats-support',links:[],where:'În QGIS 3.44, alegerea sursei de date și opțiunile disponibile depind de format și de driverele instalației.'};
  const demos=[
    {...base,id:'F0',title:'Ce este un format de date?',concept:'Aceeași zonă: obiecte vectoriale, grid raster și un fenomen în timp. Formatul influențează organizarea datelor.',observation:'Structură, serializare, metadata, georeferențiere, acces și schimb. Formatul nu schimbă realitatea geografică reprezentată.',defaults:{family:'vector'},controls:[select('family','Reprezentarea conceptuală','vector',[['vector','Vector'],['raster','Raster'],['cube','Multidimensional']])]},
    {...base,id:'F1',title:'Vector clasic · Shapefile → GeoPackage → GeoJSON',concept:'Aceleași features, trei organizări. Alege formatul pentru a inspecta structura.',observation:'Legacy nu înseamnă inutil: compatibilitatea cu un sistem vechi poate justifica Shapefile.',defaults:{format:'gpkg',answer:''},controls:[select('format','Formatul inspectat','gpkg',formatOptions(['shp','gpkg','geojson'])),select('answer','Trei layere pentru un coleg în QGIS: ce alegi?','',[['','Alege'],...formatOptions(['shp','gpkg','geojson'])])],links:[['geospatial-data.html#formats','Date geospațiale · formate']]},
    {...base,id:'F2',title:'Vector modern · FlatGeobuf → GeoParquet',concept:'Ambele sunt moderne, dar urmăresc fluxuri diferite: features și index spațial, respectiv coloane și analiză.',observation:'Accesul desenat este conceptual: nu rulează un cititor FlatGeobuf sau un query engine Parquet.',defaults:{format:'fgb',subset:'nw',query:'hospital',geometry:false},controls:[select('format','Organizarea inspectată','fgb',formatOptions(['fgb','geoparquet'])),select('subset','Bbox solicitat','nw',subsetOptions,['format','fgb']),select('query','Query conceptual','hospital',[['hospital','type = hospital'],['school','type = school'],['all','Toate atributele']],['format','geoparquet']),{type:'checkbox',key:'geometry',label:'Include și geometria în rezultat',value:false,when:['format','geoparquet']}]},
    {...base,id:'F3',title:'Raster · GeoTIFF → COG',concept:'Aceeași informație raster; organizarea accesului este cea comparată. COG este un GeoTIFF organizat pentru acces selectiv.',observation:'HTTP Range necesită un client și un server compatibile. Schema nu execută request-uri și nu măsoară trafic sau viteze.',defaults:{format:'cog',subset:'nw',level:'0'},controls:[select('format','Organizarea rasterului','cog',formatOptions(['geotiff','cog'])),select('subset','Zona solicitată','nw',subsetOptions),select('level','Rezoluția conceptuală','0',[['0','Bază · 6 × 6'],['1','Overview 1 · 3 × 3'],['2','Overview 2 · 2 × 2']])],links:[['raster-styling.html','Raster Styling']]},
    {...base,id:'F4',title:'NetCDF · date multidimensionale',concept:'Dimensions → coordinates → variables → attributes. Selectează o variabilă și un moment pentru a extrage un slice 2D.',observation:'NetCDF-4 poate utiliza HDF5 cu chunking și compresie. Numărul momentelor nu definește singur numărul benzilor unui raster.',defaults:{variable:'temperature',time:0},controls:[select('variable','Variable','temperature',Object.entries(F.variables).map(([id,v])=>[id,v.label])),{type:'range',key:'time',label:'Time · index 0–5 (t1–t6)',value:0,min:0,max:5,step:1,unit:''}]},
    {...base,id:'F5',title:'Zarr · cuburi și chunks',concept:'Array N-D → chunks → adresare selectivă. Selectează intervalul temporal și bbox-ul.',observation:'Chunks independente se potrivesc cu filesystem, key/value stores și object storage. Zarr poate fi folosit și local.',defaults:{subset:'nw',from:'1',to:'1'},controls:[select('from','Time · de la','1',times),select('to','Time · până la','1',times),select('subset','Spatial subset / bbox','nw',subsetOptions)]},
    {...base,id:'F6',title:'NetCDF vs Zarr · același cub',concept:'Același temperature(time, lat, lon), aceleași valori. Comparăm modelul de stocare și acces.',observation:'Alegerea depinde de ecosistem, compatibilitate și pattern-ul de acces; chunking-ul nu este exclusiv Zarr.',defaults:{time:'1',choice:''},controls:[select('time','Time · pentru ambele reprezentări','1',times),select('choice','20 de ani de date orare; subseturi mici dintr-un object store','',[['','Alege o perspectivă'],['netcdf','NetCDF'],['zarr','Zarr'],['depends','Depinde de ecosistem și acces']])]},
    {...base,id:'F7',title:'Alege formatul potrivit',level:'APLICARE',concept:'Nouă scenarii deterministe. Citește cerințele și compară potrivirea cu fluxul de lucru.',observation:'Recomandarea privește scenariul descris; alte alegeri pot fi posibile cu alte cerințe.',defaults:{scenario:'0',answer:''},controls:[select('scenario','Scenariul curent','0',F.scenarios.map((s,i)=>[String(i),(i+1)+' · '+F.byId[s.recommended].family])),select('answer','Formatul propus','',[['','Alege un format'],...formatOptions(F.formats.map(f=>f.id))])]},
    {...base,id:'F8',title:'Format Explorer · Potrivit pentru ce?',level:'APLICARE',concept:'Compară oricare două formate pe aceleași axe. Nu există winner, scor sau clasament.',observation:'Compatibilitatea reală depinde de versiuni, extensii, convenții, CRS, tipuri de câmpuri și software.',defaults:{a:'gpkg',b:'geojson'},controls:[select('a','Format A','gpkg',formatOptions(F.formats.map(f=>f.id))),select('b','Format B','geojson',formatOptions(F.formats.map(f=>f.id)))]}
  ];
  const txt=(x,y,t,extra='')=>`<text x="${x}" y="${y}" ${extra}>${esc(t)}</text>`,rect=(x,y,w,h,label,selected=false)=>`<g${selected?' data-selected="true"':''}><rect x="${x}" y="${y}" width="${w}" height="${h}" class="${selected?'fmt-selected':'fmt-block'}"/>${label?txt(x+8,y+23,label):''}</g>`;
  function frame(id,title,desc,body,w=520,h=430){return `<svg class="formats-scene" role="img" viewBox="0 0 ${w} ${h}" aria-labelledby="${id}-svg-title ${id}-svg-desc"><title id="${id}-svg-title">${esc(title)}</title><desc id="${id}-svg-desc">${esc(desc)}</desc><defs><pattern id="${id}-hatch" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="#245b78" stroke-width="1"/></pattern></defs>${body}</svg>`;}
  const poly=(points,cls,extra='')=>`<polygon points="${points.map(p=>p.join(',')).join(' ')}" class="${cls}" ${extra}/>`;
  const project=(x,y,z)=>[65+x*44+y*16,365-y*16-z*38];
  function cube(id,variable,time,chunkIds=null){let body='';if(chunkIds){const selected=new Set(chunkIds);for(const c of M.chunks){const x=c.c*2+.08,y=c.r*2+.08,z=c.t*2+.08,p=(dx,dy,dz)=>project(x+dx,y+dy,z+dz),on=selected.has(c.id);body+=`<g data-chunk="${c.id}" data-relevant="${on}">${poly([p(0,0,0),p(1.84,0,0),p(1.84,0,1.84),p(0,0,1.84)],on?'fmt-chunk-selected':'fmt-chunk')}${poly([p(1.84,0,0),p(1.84,1.84,0),p(1.84,1.84,1.84),p(1.84,0,1.84)],on?'fmt-chunk-selected':'fmt-chunk')}${poly([p(0,0,1.84),p(1.84,0,1.84),p(1.84,1.84,1.84),p(0,1.84,1.84)],on?'fmt-chunk-selected':'fmt-chunk')}${txt(...p(.15,0,.6),c.id,'class="fmt-chunk-id"')}${on?txt(...p(1.35,0,1.1),'✓','class="fmt-chunk-id"'):''}</g>`;}}
    else{for(let t=0;t<6;t++){const z=t+.5,on=t===+time;body+=`<g data-plane="${t}" data-relevant="${on}">${poly([project(0,0,z),project(6,0,z),project(6,6,z),project(0,6,z)],on?'fmt-plane-selected':'fmt-plane')}${on?poly([project(0,0,z),project(6,0,z),project(6,6,z),project(0,6,z)],'fmt-hatched',`style="fill:url(#${id}-hatch)"`):''}${txt(442,project(6,6,z)[1]+5,'t'+(t+1)+(on?' ✓':''))}</g>`;}}
    body+=`<path class="fmt-axis" d="M55 375H350 M55 375L30 320 M55 375V35"/>${txt(190,407,'LON / x')}${txt(13,306,'LAT / y')}${txt(8,27,'TIME')}`;
    return frame(id,chunkIds?'Zarr · cub chunked':'NetCDF · cub multidimensional',chunkIds?'Chunks relevante: '+chunkIds.join(', '):F.variables[variable].label+', plan selectat t'+(+time+1)+'. Axele: time, lat, lon.',body);}
  function grid(id,variable,time){const a=M.slice(variable,+time),v=F.variables[variable];let body=txt(30,28,v.label+' · t'+(+time+1)+' · '+v.units);for(let r=0;r<6;r++)for(let c=0;c<6;c++){const n=a[r][c],color=variable==='temperature'?`hsl(${210-n*3},55%,${90-n}%)`:`hsl(210,65%,${92-n*2}%)`;body+=`<g data-cell="${r}-${c}" data-value="${n}"><rect x="${40+c*49}" y="${45+r*39}" width="49" height="39" fill="${color}" stroke="#456779"/>${txt(64+c*49,70+r*39,n.toFixed(1),'text-anchor="middle" class="fmt-value"')}</g>`;}return frame(id,'Selected slice · 2D',v.longName+'. Valori sintetice, lat × lon; '+v.units,body,380,300);}
  function points(id,selected=null,subset=null){const ids=selected?new Set(selected.map(f=>f.id)):null;let body=rect(35,45,330,250,'');if(subset){const b=F.subsets[subset].box;body+=`<rect class="fmt-bbox" x="${35+b[0]*55}" y="${45+b[1]*40}" width="${(b[2]-b[0])*55}" height="${(b[3]-b[1])*40}"/>`;}for(const f of F.features){body+=`<g data-feature="${f.id}" data-relevant="${!ids||ids.has(f.id)}"><circle cx="${35+f.x*55}" cy="${45+f.y*40}" r="8" class="${ids?.has(f.id)?'fmt-selected':'fmt-point'}"/>${txt(46+f.x*55,40+f.y*40,f.id,'class="fmt-small"')}</g>`;}return frame(id,'Zonă sintetică · features',selected?'Features relevante: '+selected.map(f=>f.id).join(', '):'Aceeași zonă conceptuală, cu douăsprezece obiecte vectoriale.',body,420,320);}
  const sourceLinks=ids=>`<aside class="formats-references" aria-label="Surse pentru această secțiune"><strong>Specificații și suport</strong><ul>${[...new Set(ids)].map(id=>`<li><a href="${esc(F.sources[id].url)}" target="_blank" rel="noopener noreferrer">${esc(F.sources[id].title)} ↗</a></li>`).join('')}</ul></aside>`;
  function facts(f,keys=['structure','crs','standardStatus','limitations']){return `<article class="format-facts" data-format="${f.id}"><h4>${esc(f.name)}</h4><dl>${keys.map(key=>`<div data-axis="${key}"><dt>${esc(F.axes.find(a=>a[0]===key)?.[1]||key)}</dt><dd>${esc(f[key])}</dd></div>`).join('')}</dl></article>`;}
  function structure(id,format){let b=txt(30,30,F.byId[format].name);if(format==='shp'){for(const [i,row] of [['roads.shp','geometrie'],['roads.shx','index asociat'],['roads.dbf','atribute'],['roads.prj','CRS, dacă există']].entries())b+=rect(30,55+i*54,210,44,row[0])+txt(260,82+i*54,row[1]);b+=txt(55,310,'↓ un singur dataset logic');}
    else if(format==='gpkg'){b+=rect(50,50,390,265,'project.gpkg · SQLite container');['roads · buildings · stations','attributes','spatial indexes','metadata / extensions','tile matrix data'].forEach((s,i)=>b+=txt(70,110+i*40,s));}
    else{['{ "type": "Feature",','  "geometry": { … },','  "properties": { … }','}'].forEach((s,i)=>b+=txt(40,85+i*45,s));b+=txt(40,285,'JSON text · RFC 7946');}return frame(id,'Organizarea datelor',F.byId[format].structure,b,520,350);}
  function draw(d,s,id){let svg='',status='',dynamic='',legend=[];const refs={F0:['qgis'],F1:['gpkg','geojson','shp'],F2:['fgb','geoparquet','parquetStatus'],F3:['geotiff','cog'],F4:['netcdfModel','netcdfStorage','gdalNetcdf'],F5:['zarr','zarrSpec','gdalZarr'],F6:['netcdfStorage','zarr'],F7:['qgis'],F8:[]};
    if(d.id==='F0'){svg=s.family==='vector'?points(id):s.family==='raster'?grid(id,'temperature',0):cube(id,'temperature',0);status='Reprezentare: '+({vector:'features vectoriale',raster:'grid raster',cube:'array multidimensional'}[s.family])+'. Zona și fenomenul conceptual rămân aceleași.';dynamic='<p>Vector: obiecte cu geometrie și atribute. Raster: valori pe celule. Multidimensional: aceeași grilă, mai multe variabile și momente. Modelul și encoding-ul sunt alegeri diferite.</p>';}
    if(d.id==='F1'){svg=structure(id,s.format);status=M.feedback(0,s.answer);dynamic=`<div class="formats-classic">${['shp','gpkg','geojson'].map(f=>facts(F.byId[f],['structure','multipleLayers','typicalUses'])).join('')}</div><p>Features conceptuale identice în toate cele trei organizări:</p>${points(id+'-same')}<p>${esc(F.byId[s.format].crs)}</p>`;}
    if(d.id==='F2'){if(s.format==='fgb'){const selected=M.spatial(s.subset);svg=points(id,selected,s.subset);let b=rect(25,25,470,45,'HEADER · CRS / schema')+rect(25,82,470,45,'INDEX spațial · opțional');for(const [i,f] of F.features.entries())b+=rect(25+(i%3)*160,145+Math.floor(i/3)*50,150,42,f.block+' · '+f.id,selected.includes(f));dynamic=frame(id+'-blocks','FlatGeobuf · blocuri relevante','Selecție conceptuală după bbox; nu intervale reale de bytes.',b,520,365)+facts(F.byId.fgb,['randomAccess','streaming','limitations']);status='Bbox: '+F.subsets[s.subset].label+'. Blocuri conceptual relevante: '+(selected.map(f=>f.block).join(', ')||'niciunul')+'.';}
      else{const q=M.columns(s.query,s.geometry);let b=txt(25,27,'ROW ORIENTED');F.features.slice(0,3).forEach((f,i)=>b+=rect(25,42+i*45,470,36,f.id+' / '+f.type+' / '+f.name+' / geometry'));b+=txt(25,208,'COLUMNAR · coloane solicitate');['id','type','name','geometry'].forEach((k,i)=>b+=rect(25,223+i*42,470,35,k+' [ … ]'+(q.columns.includes(k)?' ✓':''),q.columns.includes(k)));svg=frame(id,'GeoParquet · row vs columnar','Coloane relevante: '+q.columns.join(', '),b);status='Query conceptual: '+s.query+'. Coloane: '+q.columns.join(', ')+'. Features: '+q.features.map(f=>f.id).join(', ')+'.';dynamic=facts(F.byId.geoparquet,['columnar','randomAccess','standardStatus','limitations']);}}
    if(d.id==='F3'){const tiles=M.tiles(s.subset,s.level),selected=tiles.filter(t=>t.selected);let b=txt(25,30,'Aceleași valori raster · '+F.byId[s.format].name);for(let l=0;l<3;l++)b+=rect(25,50+l*47,470,38,(l?'Overview '+l:'Rezoluția de bază')+(s.format==='cog'&&+s.level===l?' ✓':''),s.format==='cog'&&+s.level===l);for(const t of tiles){const [x,y,x2,y2]=t.box;b+=`<g data-tile="${t.id}" data-relevant="${s.format==='cog'&&t.selected}">${rect(55+x*56,205+y*30,(x2-x)*56,(y2-y)*30,t.id,s.format==='cog'&&t.selected)}</g>`;}svg=frame(id,'GeoTIFF / COG · acces','Schema blocurilor solicitate și nivelul selectat; rasterul nu se modifică.',b);status=s.format==='cog'?'Nivel '+s.level+'; '+F.subsets[s.subset].label+' → '+selected.map(t=>t.id).join(', ')+'. HTTP Range: numai blocurile necesare, dacă serverul suportă Range.':'GeoTIFF generic: accesul poate folosi blocuri, dar organizarea nu garantează cerințele COG.';dynamic=grid(id+'-unchanged','temperature',0)+facts(F.byId[s.format],['structure','randomAccess','standardStatus']);}
    if(d.id==='F4'){const v=F.variables[s.variable];svg=`<div class="formats-cube-grid"><figure>${cube(id,s.variable,s.time)}<figcaption>Variable: ${v.label}. Selected slice: t${+s.time+1}.</figcaption></figure><figure>${grid(id+'-slice',s.variable,s.time)}<figcaption>Selected slice · lat × lon · ${v.units}</figcaption></figure></div>`;status=`Variable: ${v.label}; time = t${+s.time+1}; ${s.variable}(time, lat, lon) → slice 2D, ${v.units}. Aceasta este o secțiune 2D a unei variabile multidimensionale.`;dynamic=`<div class="formats-model"><section><h4>DIMENSIONS</h4><p>time = 6 · lat = 6 · lon = 6</p></section><section><h4>COORDINATES</h4><p>time = t1…t6<br>lat = 44…49 · lon = 20…25</p></section><section><h4>VARIABLES</h4><p>temperature(time, lat, lon)<br>precipitation(time, lat, lon)</p></section><section><h4>ATTRIBUTES</h4><p>units: ${v.units}<br>long_name: ${v.longName}<br>calendar: standard</p></section></div><p>Coordonate și valori sintetice; time este o axă conceptuală, nu altitudine. NetCDF-4 / HDF5 poate utiliza chunking și compresie.</p>`;}
    if(d.id==='F5'){const selected=M.selectedChunks(s.subset,s.from,s.to),ids=selected.map(c=>c.id),lo=Math.min(+s.from,+s.to),hi=Math.max(+s.from,+s.to),b=F.subsets[s.subset].box;svg=cube(id,'temperature',lo,ids);status=`Selected subset: time = t${lo+1}…t${hi+1}; lat = rows ${b[1]}…${b[3]-1}; lon = cols ${b[0]}…${b[2]-1}. Relevant chunks: ${ids.join(', ')} (${ids.length} / ${M.chunks.length}).`;dynamic=`<h4>Metadata → chunk objects</h4><dl class="formats-meta"><dt>shape</dt><dd>[6, 6, 6] · time, lat, lon</dd><dt>chunk shape</dt><dd>[2, 2, 2]</dd><dt>dtype</dt><dd>float32, conceptual</dd><dt>compressor</dt><dd>Configurabil în store; nu simulăm un codec.</dd><dt>dimensions / attributes</dt><dd>Convențiile leagă dimensiunile, units și CRS.</dd></dl><p>IDs C01–C27 sunt etichete didactice, nu chei obligatorii Zarr. Schema nu pretinde o structură de fișiere V3.</p><p>Chunks relevante: <strong>${ids.join(', ')}</strong>. Se citesc chunks care intersectează cererea, apoi se extrage subsetul din ele.</p>`;}
    if(d.id==='F6'){const ids=M.selectedChunks('nw',s.time).map(c=>c.id);svg=`<div class="formats-pair"><section><h4>NetCDF · temperature</h4>${cube(id+'-nc','temperature',s.time)}${grid(id+'-nc-slice','temperature',s.time)}</section><section><h4>Zarr · temperature</h4>${cube(id+'-za','temperature',s.time,ids)}${grid(id+'-za-slice','temperature',s.time)}</section></div>`;status='Același temperature(time, lat, lon), time = t'+(+s.time+1)+'. Valorile ambelor slices sunt identice.'+(s.choice?' Pentru subseturi mici dintr-un object store, Zarr merită evaluat; NetCDF rămâne posibil, în funcție de encoding, servicii și compatibilitate.':'');dynamic=`<div class="formats-pair">${facts(F.byId.netcdf,['structure','chunked','cloudFriendly'])}${facts(F.byId.zarr,['structure','chunked','cloudFriendly'])}</div><p>Nu comparăm vechi/nou sau viteze universale. NetCDF-4 poate avea chunks interne; Zarr pune adresarea chunks în centrul modelului de storage. Performanța depinde de implementare, compresie, chunks, server și cereri.</p>`;}
    if(d.id==='F7'){const scenario=F.scenarios[+s.scenario];svg=`<section class="formats-scenario"><span class="eyebrow">${+s.scenario+1} / 9</span><h4>${esc(scenario.question)}</h4><p>Compară familia de date, organizarea și modul de acces cerut.</p></section>`;status=M.feedback(s.scenario,s.answer);dynamic=s.answer?facts(F.byId[s.answer],['typicalUses','limitations']):'<p>Recomandările sunt contextuale, fără clasament sau scor persistent.</p>';}
    if(d.id==='F8'){svg=`<div class="formats-pair formats-explorer" aria-label="Comparație pe aceleași criterii">${facts(F.byId[s.a],F.axes.map(a=>a[0]))}${facts(F.byId[s.b],F.axes.map(a=>a[0]))}</div>`;status=s.a===s.b?'Ai selectat același format: aceleași informații, fără clasament.':'Format A: '+F.byId[s.a].name+' · Format B: '+F.byId[s.b].name+'. Potrivit pentru ce?';dynamic=sourceLinks([...F.byId[s.a].sources.slice(0,2),...F.byId[s.b].sources.slice(0,2)])+`<p>Status verificat la ${F.verifiedOn}; verifică versiunea și driverele instalației QGIS înainte de schimbul datelor.</p>`;}
    if(!['F8'].includes(d.id))dynamic+=sourceLinks(refs[d.id]);return {svg,status,dynamic,legend,where:base.where};
  }
  const controllers=new Map();document.getElementById('formats-root').innerHTML=demos.map(L.shell).join('');for(const d of demos){const card=document.getElementById(d.id);card.classList.add('formats-demo');if(['F4','F5','F6','F8'].includes(d.id)){card.classList.add('formats-wide');card.querySelector('.lab-demo-layout').prepend(card.querySelector('.lab-controls'));}
    const c=L.mountDemo(d,card,{draw,onChange:(s,key)=>{if(d.id==='F7'&&key==='scenario')s.answer='';},afterRender:(s,out,card)=>{const ids=d.id==='F1'?[s.format]:d.id==='F2'?[s.format]:d.id==='F3'?[s.format]:d.id==='F4'?['netcdf']:d.id==='F5'?['zarr']:d.id==='F6'?['netcdf','zarr']:d.id==='F8'?[s.a,s.b]:[];card.querySelector('.qgis-path').textContent=ids.length?[...new Set(ids)].map(id=>F.byId[id].name+': '+F.byId[id].qgisSupport).join(' '):base.where;}});controllers.set(d.id,c);}
  L.checkpoint(document.getElementById('formats-checkpoint'),F.checkpoint,{title:'Checkpoint · Formate & interoperabilitate',id:'formats-checkpoint-title',namespace:'formats-quiz'});
  document.getElementById('formats-qgis-root').innerHTML=L.sources(['formats-support'],{id:'formats-qgis-sources',title:'Continuă în QGIS · formate și compatibilitate'});
  root.CARTO_FORMATS_LAB={controllers,draw,demos,cube,grid};const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target)requestAnimationFrame(()=>target.scrollIntoView({block:'start',behavior:'instant'}));
})(window);
