'use strict';
(() => {
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const setPressed=(selector,active)=>$$(selector).forEach(b=>b.setAttribute('aria-pressed',String(b===active)));
  const svg=(element,html)=>element.innerHTML=html;
  const bg='<rect width="400" height="240" fill="var(--surface-alt)"/>';
  const park='<path d="M240 30L370 48 345 185 230 209 203 105Z" fill="var(--teal)" fill-opacity=".27" stroke="var(--teal)" stroke-width="3"/>';
  const road='<path d="M15 174Q99 91 194 140T390 47" fill="none" stroke="var(--blue)" stroke-width="7"/>';
  const school='<circle cx="139" cy="88" r="9" fill="var(--blue)" stroke="var(--surface)" stroke-width="2"/>';
  svg($('#model-vector-svg'),`${bg}${park}${road}${school}<text x="35" y="36" fill="var(--ink)">punct · linie · poligon</text>`);
  const rasterCells=Array.from({length:10*16},(_,i)=>{const x=i%16,y=Math.floor(i/16);const inPark=x>8&&x<15&&y>1&&y<9;const nearRoad=Math.abs(y-(7-0.36*x))<1.4;const color=inPark?'var(--teal)':nearRoad?'var(--blue)':'var(--sand)';return `<rect x="${20+x*23}" y="${5+y*23}" width="22" height="22" fill="${color}" opacity="${inPark?.55:nearRoad?.55:.7}"/>`;}).join('');
  svg($('#model-raster-svg'),`${bg}${rasterCells}`);
  $$('[data-model]').forEach(b=>b.addEventListener('click',()=>{setPressed('[data-model]',b);$('#model-vector').hidden=b.dataset.model==='raster';$('#model-raster').hidden=b.dataset.model==='vector';}));

  const features=[
    {id:'S01',name:'Școala Centrală',type:'punct',pop:'—',category:'educație',text:'Un punct poate avea mai multe atribute, dar nu arată singur zona deservită.'},
    {id:'D02',name:'Drumul Parcului',type:'linie',pop:'—',category:'transport',text:'Geometria liniei arată traseul; viteza ori starea drumului ar fi atribute separate.'},
    {id:'P03',name:'Parcul Verde',type:'poligon',pop:'—',category:'spațiu verde',text:'Poligonul delimitează suprafața; numele și categoria sunt câmpuri în tabel.'}
  ];
  const featureShapes=[`<circle cx="155" cy="95" r="11" fill="var(--blue)" stroke="var(--surface)" stroke-width="3"/>`,`<path d="M25 220Q120 115 235 153T450 55" fill="none" stroke="var(--blue)" stroke-width="9"/>`,`<path d="M275 30L435 57 395 220 278 241 244 101Z" fill="var(--teal)" fill-opacity=".3" stroke="var(--teal)" stroke-width="3"/>`];
  svg($('#feature-svg'),`<rect width="480" height="280" fill="var(--surface-alt)"/>${featureShapes.map((shape,i)=>`<g role="button" tabindex="0" aria-label="Alege ${esc(features[i].name)}" data-feature="${i}" aria-pressed="${i===0}">${shape}</g>`).join('')}`);
  $('#feature-table').innerHTML=features.map((f,i)=>`<tr data-feature-row="${i}"><td><button type="button" data-feature="${i}">${f.id}</button></td><td>${esc(f.name)}</td><td>${f.type}</td><td>${f.pop}</td><td>${f.category}</td></tr>`).join('');
  function selectFeature(i){$$('[data-feature]').forEach(el=>el.setAttribute('aria-pressed',String(Number(el.dataset.feature)===i)));$$('[data-feature-row]').forEach(row=>row.classList.toggle('active',Number(row.dataset.featureRow)===i));$$('#feature-svg [data-feature]').forEach(node=>node.classList.toggle('feature-selected',Number(node.dataset.feature)===i));$('#feature-explain').textContent=`${features[i].id} · ${features[i].text}`;}
  $$('[data-feature]').forEach(el=>{el.addEventListener('click',()=>selectFeature(+el.dataset.feature));el.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectFeature(+el.dataset.feature);}})});selectFeature(0);

  const topology={touch:['Două poligoane au o limită comună, dar interiorul lor nu se suprapune.','<rect x="85" y="50" width="160" height="100" fill="var(--blue-soft)" stroke="var(--blue)" stroke-width="3"/><rect x="245" y="50" width="160" height="100" fill="var(--blue-soft)" stroke="var(--teal)" stroke-width="3"/>'],overlap:['Interioarele celor două geometrii au o regiune comună.','<circle cx="225" cy="95" r="69" fill="var(--blue)" fill-opacity=".27" stroke="var(--blue)" stroke-width="3"/><circle cx="293" cy="95" r="69" fill="var(--teal)" fill-opacity=".27" stroke="var(--teal)" stroke-width="3"/>'],within:['Punctul se află în interiorul poligonului ales.','<path d="M110 146L150 42 385 52 414 146Z" fill="var(--teal)" fill-opacity=".23" stroke="var(--teal)" stroke-width="3"/><circle cx="255" cy="94" r="10" fill="var(--blue)"/>'],connect:['Două linii se întâlnesc într-un nod; conectivitatea rețelei trebuie definită explicit.','<path d="M90 145L260 95 421 145 M260 95L260 28" fill="none" stroke="var(--blue)" stroke-width="6"/><circle cx="260" cy="95" r="9" fill="var(--teal)"/>']};
  function drawTopology(key){const [note,shape]=topology[key];svg($('#topology-svg'),`<rect width="530" height="190" fill="var(--surface-alt)"/>${shape}`);$('#topology-explain').textContent=note;}
  $$('[data-topology]').forEach(b=>b.addEventListener('click',()=>{setPressed('[data-topology]',b);drawTopology(b.dataset.topology)}));drawTopology('touch');

  $('#format-grid').innerHTML=window.CARTO_GEOSPATIAL_FORMATS.map(f=>`<article data-content-type="concept" data-theme="${f.model.includes('raster')?'raster':'vector'}"><span class="source-tag qgis-tag">${esc(f.model.toUpperCase())}</span><h3>${esc(f.name)} <small>${esc(f.extension)}</small></h3><p>${esc(f.common_use)}</p><p><strong>Avantaj:</strong> ${esc(f.advantages)}</p><p><strong>Limită:</strong> ${esc(f.limitations)}</p><a href="${esc(f.official_source)}" target="_blank" rel="noopener noreferrer">Documentația oficială ↗</a></article>`).join('');

  const height=(x,y)=>320+250*Math.exp(-((x-.36)**2+(y-.55)**2)/.075)+190*Math.exp(-((x-.77)**2+(y-.31)**2)/.045)+55*x;
  const modes={dem:{unit:'m',value:(x,y)=>Math.round(height(x,y)),color:v=>`hsl(${196-(v-300)*.13} 49% ${73-(v-300)*.045}%)`,meaning:v=>`altitudine schematică ${v} m`},land:{unit:'cod',value:(x,y)=>x+y<.75?1:x>.62&&y<.65?3:2,color:v=>({1:'var(--sand)',2:'var(--blue-soft)',3:'var(--teal)'})[v],meaning:v=>({1:'1 = construit',2:'2 = altă acoperire',3:'3 = pădure'})[v]},loss:{unit:'cod didactic',value:(x,y)=>x>.65&&y<.5?2:x>.25&&x<.55&&y>.58?1:0,color:v=>({0:'var(--surface)',1:'var(--sand)',2:'var(--teal)'})[v],meaning:v=>({0:'0 = fără eveniment în această SCHEMĂ',1:'1 = cod A',2:'2 = cod B'})[v]}};
  let selectedPixel=0;
  function drawRaster(){const mode=modes[$('#raster-mode').value],n=8;$('#raster-grid').style.setProperty('--cols',n);$('#raster-grid').innerHTML=Array.from({length:n*n},(_,i)=>{const r=Math.floor(i/n),c=i%n,v=mode.value((c+.5)/n,(r+.5)/n);return `<button type="button" data-pixel="${i}" aria-label="Rând ${r+1}, coloană ${c+1}, valoare ${v}" style="background:${mode.color(v)}" class="${i===selectedPixel?'selected':''}">${$('#raster-mode').value==='dem'?v:''}</button>`}).join('');inspectPixel(selectedPixel);}
  function inspectPixel(i){selectedPixel=i;const n=8,r=Math.floor(i/n),c=i%n,mode=modes[$('#raster-mode').value],v=mode.value((c+.5)/n,(r+.5)/n);$$('[data-pixel]').forEach(b=>b.classList.toggle('selected',+b.dataset.pixel===i));$('#pixel-info').textContent=`Rând ${r+1} · coloană ${c+1} · valoare ${v} ${mode.unit}. ${mode.meaning(v)}.`;}
  $('#raster-grid').addEventListener('click',e=>{const b=e.target.closest('[data-pixel]');if(b)inspectPixel(+b.dataset.pixel)});$('#raster-mode').addEventListener('change',drawRaster);drawRaster();
  const resolution=[['1000 m',2],['500 m',4],['250 m',8],['100 m',20]];
  function drawResolution(){const [label,n]=resolution[+$('#resolution-slider').value];$('#resolution-out').textContent=label;$('#resolution-grid').style.setProperty('--cols',n);$('#resolution-grid').innerHTML=Array.from({length:n*n},(_,i)=>{const v=height(((i%n)+.5)/n,(Math.floor(i/n)+.5)/n);return `<span style="background:${modes.dem.color(v)}"></span>`}).join('');$('#resolution-explain').textContent=`Aceeași întindere schematică de 2 km × 2 km are ${n} × ${n} = ${n*n} celule la ${label}.`;}$('#resolution-slider').addEventListener('input',drawResolution);drawResolution();

  const operations=window.CARTO_PROCESSING_OPERATIONS;
  function operationDetail(op){
    const isVector=op.model==='vector';
    const controls=op.id==='vector-buffer'?'<label class="op-slider" for="buffer-range">Raza schematică: <output id="buffer-out">500 m</output><input id="buffer-range" type="range" min="250" max="2000" step="250" value="500"></label><p class="geo-note">Eticheta este în metri numai în contextul unui CRS proiectat adecvat; desenul nu folosește coordonate reale.</p>':op.id==='raster-hillshade'?'<label class="op-slider" for="light-range">Azimutul luminii: <output id="light-out">300°</output><input id="light-range" type="range" min="0" max="360" step="15" value="300"></label>':'';
    const links=[op.qgis_url?`<a href="${esc(op.qgis_url)}" target="_blank" rel="noopener noreferrer">Vezi în QGIS 3.44 <span class="sr-only">(filă nouă)</span>↗</a>`:'',...op.tutorial_links.map(link=>`<a href="${esc(link)}">Vezi în ${link.match(/t\d\d/i)?.[0].toUpperCase()||'tutorial'} →</a>`),...op.theory_links.map(link=>`<a href="${esc(link)}">Vezi conceptul →</a>`)].join('');
    return `<span class="eyebrow">${isVector?'VECTOR':'RASTER'} · ${esc(op.category)}</span><h3 id="${esc(op.id)}-title">${esc(op.name_ro)}</h3><p>${esc(op.summary_ro)}</p><div class="operation-flow"><span>Intrare<br><strong>${esc(op.input.join(' + '))}</strong></span><b>→</b><span>Operație<br><strong>${esc(op.name_ro)}</strong></span><b>→</b><span>Rezultat<br><strong>${esc(op.output)}</strong></span></div>${controls}<div class="operation-schema-host">${window.CARTO_PROCESSING_DIAGRAMS.render(op)}</div><p class="operation-example"><strong>Exemplu:</strong> ${esc(op.example_ro)}</p><div class="operation-links">${links}</div>`;
  }
  function initOperations(model){
    const list=operations.filter(o=>o.model===model), picker=$(`#${model}-operations`),detail=$(`#${model}-operation-detail`);
    picker.innerHTML=list.map((o,i)=>`<button type="button" data-operation="${esc(o.id)}" aria-controls="${model}-operation-detail" aria-pressed="${i===0}">${esc(o.name_ro)}</button>`).join('');
    const show=id=>{const op=list.find(o=>o.id===id);if(!op)return;detail.innerHTML=operationDetail(op);detail.setAttribute("aria-labelledby",`${op.id}-title`);$$(`#${model}-operations button`).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.operation===id)));const schema=detail.querySelector('.operation-schema-host');if(id==='vector-buffer')detail.querySelector('#buffer-range').addEventListener('input',e=>{detail.querySelector('#buffer-out').textContent=`${e.target.value} m`;schema.innerHTML=window.CARTO_PROCESSING_DIAGRAMS.render(op,{distance:+e.target.value})});if(id==='raster-hillshade')detail.querySelector('#light-range').addEventListener('input',e=>{detail.querySelector('#light-out').textContent=`${e.target.value}°`;schema.innerHTML=window.CARTO_PROCESSING_DIAGRAMS.render(op,{azimuth:+e.target.value})});};
    picker.addEventListener('click',e=>{const b=e.target.closest('[data-operation]');if(b)show(b.dataset.operation)});show(list[0].id);
  }
  initOperations('vector');initOperations('raster');
  const answers={hospitals:['Punct vectorial','Spitalele sunt entități discrete cu localizare și atribute; o hartă de densitate raster ar fi un produs derivat.'],river:['Linie vectorială','Traseul discret poate păstra segmente și conexiuni; un raster hidrologic poate servi altor analize.'],park:['Poligon vectorial','Limita administrată este o geometrie delimitată cu atribute.'],elevation:['Raster continuu','Un DEM eșantionează înălțimea pe o grilă; curbele de nivel sunt o reprezentare vectorială derivată.'],temperature:['Raster continuu','O suprafață interpolată descrie estimări între observații; punctele inițiale rămân vectoriale.'],population:['Depinde de sursă și întrebare','T05 folosește un grid vectorial de poligoane cu atribute. O versiune raster ar reprezenta valori pe pixeli; nu presupune că orice grid este raster.']};
  function choose(){const [title,why]=answers[$('#data-question').value];$('#data-answer').innerHTML=`<strong>${esc(title)}</strong><p>${esc(why)}</p>`;}$('#data-question').addEventListener('change',choose);choose();
})();
