/* Small shared components for local educational GIS laboratories. */
(function(root){
  'use strict';
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sourceLabels={'arrow-symbols':'Manual QGIS: simboluri și symbol layers','symbology':'Tutorial QGIS: Symbology','classification':'Tutorial QGIS: Categorized, Graduated și Rule-based','vector-styling':'Manual QGIS: renderere și vizibilitate'};
  function sourceLink(id,label){const source=root.CARTO_QGIS_LINKS?.links.find(s=>s.id===id);if(!source?.verified)return '';return `<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(label||sourceLabels[id]||source.title)}; se deschide într-o filă nouă">${esc(label||sourceLabels[id]||source.title)} ↗</a>`;}
  function sources(ids){return `<section class="lab-sources" id="qgis-sources" aria-labelledby="qgis-sources-title"><span class="eyebrow">QGIS 3.44 · SURSE OFICIALE</span><h2 id="qgis-sources-title">Continuă în QGIS</h2><p>Laboratorul explică interactiv concepte disponibile în QGIS 3.44. Pentru fluxul complet și toate opțiunile, consultă documentația oficială.</p><ul>${ids.map(id=>`<li>${sourceLink(id)}<p class="small">${esc(root.CARTO_QGIS_LINKS?.links.find(s=>s.id===id)?.concept||'')}</p></li>`).join('')}</ul></section>`;}
  function compactSources(ids){return `<aside class="lab-sources lab-sources-compact" aria-label="Surse oficiale QGIS"><strong>QGIS 3.44 · Surse oficiale</strong><p class="small">Consultă documentația pentru fluxul complet de lucru.</p><nav aria-label="Documentație pentru stilizare">${ids.map(id=>sourceLink(id)).join('')}</nav><a href="#qgis-sources">Toate sursele și explicațiile ↓</a></aside>`;}
  function controls(demo){return demo.controls.map(c=>{
    const id=`${demo.id}-${c.key}`,data=`data-key="${c.key}"`,value=esc(c.value);
    const input=c.type==='select'?`<select id="${id}" ${data}>${c.options.map(([v,label])=>`<option value="${esc(v)}" ${String(v)===String(c.value)?'selected':''}>${esc(label)}</option>`).join('')}</select>`:c.type==='checkbox'?`<input id="${id}" ${data} type="checkbox" ${c.value?'checked':''}>`:c.type==='action'?`<button id="${id}" ${data} type="button" class="outline-button">${esc(c.label)}</button>`:`<input id="${id}" ${data} type="${c.type}" value="${value}" ${c.type==='range'?`min="${c.min}" max="${c.max}" step="${c.step}"`:''}>`;
    return `<div class="lab-control" data-control="${c.key}">${c.type==='action'?input:`<label for="${id}">${esc(c.label)} ${c.type==='range'?`<output for="${id}">${value}${esc(c.unit)}</output>`:''}</label>${input}`}</div>`;
  }).join('');}
  function shell(d){return `<article class="styling-demo" id="${d.id}" aria-labelledby="${d.id}-title"><header><span class="eyebrow">${d.id} · ${['S9','S10','S11','S12','S13','S14','S15'].includes(d.id)?'APLICARE':'EXPLORARE'}</span><h3 id="${d.id}-title">${esc(d.title)}</h3><p>${esc(d.concept)}</p></header><div class="lab-demo-layout"><div class="lab-visual"><figure class="lab-map"></figure><div class="lab-compare" hidden></div><ul class="lab-legend" aria-label="Legendă"></ul><p class="lab-status small" role="status" aria-live="polite" aria-atomic="true"></p></div><div class="lab-controls" role="group" aria-label="Controale ${esc(d.title)}">${controls(d)}<div class="lab-extra"></div></div></div><div class="lab-observe"><h4>Ce observăm</h4><p>${esc(d.observation)}</p><div class="lab-dynamic"></div></div><div class="lab-actions"><button type="button" class="outline-button" data-reset>Resetează<span class="sr-only"> ${d.id}</span></button>${['S5','S7','S14','S16'].includes(d.id)?'<button type="button" class="outline-button" data-compare aria-pressed="false">Compară</button>':''}</div><div class="lab-qgis"><h4>În QGIS</h4><p class="qgis-path">${esc(d.where)}</p>${sourceLink(d.source)}${d.links.length?`<nav aria-label="Continuă studiul">${d.links.map(([href,label])=>`<a href="${esc(href)}">${esc(label)} →</a>`).join('')}</nav>`:''}</div></article>`;}
  root.CARTO_LAB={esc,sourceLink,sources,compactSources,controls,shell};
})(window);
