/* Small shared components for local educational GIS laboratories. */
(function(root){
  'use strict';
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sourceLabels={'arrow-symbols':'Manual QGIS: simboluri și symbol layers','symbology':'Tutorial QGIS: Symbology','classification':'Tutorial QGIS: Categorized, Graduated și Rule-based','vector-styling':'Manual QGIS: renderere și vizibilitate','labels':'Tutorial QGIS: Labels','label-settings':'Manual QGIS: Label Settings','vector-layer-rendering':'Manual QGIS: Layer rendering și opacity','symbol-opacity':'Manual QGIS: Symbol opacity','color-opacity':'Manual QGIS: Fill color și alpha','group-rendering':'Manual QGIS: Render Layers as a Group'};
  function sourceLink(id,label){const source=root.CARTO_QGIS_LINKS?.links.find(s=>s.id===id);if(!source?.verified)return '';return `<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(label||sourceLabels[id]||source.title)}; se deschide într-o filă nouă">${esc(label||sourceLabels[id]||source.title)} ↗</a>`;}
  function sources(ids,{id="qgis-sources",title="Continuă în QGIS"}={}){return `<section class="lab-sources" id="${id}" aria-labelledby="${id}-title"><span class="eyebrow">QGIS 3.44 · SURSE OFICIALE</span><h2 id="${id}-title">${esc(title)}</h2><p>Laboratorul explică interactiv concepte disponibile în QGIS 3.44. Pentru fluxul complet și toate opțiunile, consultă documentația oficială.</p><ul>${ids.map(id=>`<li>${sourceLink(id)}<p class="small">${esc(root.CARTO_QGIS_LINKS?.links.find(s=>s.id===id)?.concept||'')}</p></li>`).join('')}</ul></section>`;}
  function compactSources(ids,{target="qgis-sources",subject="stilizare"}={}){return `<aside class="lab-sources lab-sources-compact" aria-label="Surse oficiale QGIS"><strong>QGIS 3.44 · Surse oficiale</strong><p class="small">Consultă documentația pentru fluxul complet de lucru.</p><nav aria-label="Documentație pentru ${subject}">${ids.map(id=>sourceLink(id)).join('')}</nav><a href="#${target}">Toate sursele și explicațiile ↓</a></aside>`;}
  function controls(demo){return demo.controls.map(c=>{
    const id=`${demo.id}-${c.key}`,data=`data-key="${c.key}"`,value=esc(c.value);
    if(c.type==='placement')return '<fieldset class="lab-control lab-placement" data-control="'+c.key+'"><legend>'+esc(c.label)+'</legend><div class="lab-placement-grid">'+[['NW','NV'],['N','N'],['NE','NE'],['W','V'],['centre','●'],['E','E'],['SW','SV'],['S','S'],['SE','SE']].map(([value,label])=>value==='centre'?'<span aria-hidden="true">●</span>':'<label><input type="radio" name="'+id+'" value="'+value+'" '+data+' '+(value===c.value?'checked':'')+'><span>'+label+'</span></label>').join('')+'</div></fieldset>';
    const input=c.type==='select'?`<select id="${id}" ${data}>${c.options.map(([v,label])=>`<option value="${esc(v)}" ${String(v)===String(c.value)?'selected':''}>${esc(label)}</option>`).join('')}</select>`:c.type==='checkbox'?`<input id="${id}" ${data} type="checkbox" ${c.value?'checked':''}>`:c.type==='action'?`<button id="${id}" ${data} type="button" class="outline-button">${esc(c.label)}</button>`:`<input id="${id}" ${data} type="${c.type}" value="${value}" ${c.type==='range'?`min="${c.min}" max="${c.max}" step="${c.step}"`:''}>`;
    return `<div class="lab-control" data-control="${c.key}">${c.type==='action'?input:`<label for="${id}">${esc(c.label)} ${c.type==='range'?`<output for="${id}">${value}${esc(c.unit)}</output>`:''}</label>${input}`}</div>`;
  }).join('');}
  function shell(d){return `<article class="${d.kind==='transparency'?'transparency-demo':d.kind==='repair'?'repair-demo':d.kind==='labeling'?'labeling-demo':'styling-demo'} lab-demo" id="${d.id}" aria-labelledby="${d.id}-title"><header><span class="eyebrow">${esc(d.badge||d.id)} · ${d.level||(['S9','S10','S11','S12','S13','S14','S15'].includes(d.id)?'APLICARE':'EXPLORARE')}</span><h3 id="${d.id}-title">${esc(d.title)}</h3><p>${esc(d.concept)}</p></header><div class="lab-demo-layout"><div class="lab-visual"><figure class="lab-map"></figure><div class="lab-compare" hidden></div><ul class="lab-legend" aria-label="Legendă"></ul><p class="lab-status small" role="status" aria-live="polite" aria-atomic="true"></p></div><div class="lab-controls" role="group" aria-label="Controale ${esc(d.title)}">${controls(d)}<div class="lab-extra"></div></div></div><div class="lab-observe"><h4>Ce observăm</h4><p>${esc(d.observation)}</p><div class="lab-dynamic"></div></div><div class="lab-actions"><button type="button" class="outline-button" data-reset>${esc(d.resetLabel||'Resetează')}<span class="sr-only"> ${esc(d.actionContext||d.id)}</span></button>${(d.compare||['S5','S7','S14','S16'].includes(d.id))?'<button type="button" class="outline-button" data-compare aria-pressed="false">Compară</button>':''}</div><div class="lab-qgis"><h4>În QGIS</h4><p class="qgis-path">${esc(d.where)}</p>${sourceLink(d.source)}${d.links.length?`<nav aria-label="Continuă studiul">${d.links.map(([href,label])=>`<a href="${esc(href)}">${esc(label)} →</a>`).join('')}</nav>`:''}</div></article>`;}
  // Shared state and checkpoint behavior; renderers remain specific to their subject.
  function checkpoint(host,items,{title='Checkpoint · Stilizare',id='checkpoint-title',namespace='quiz'}={}){
    const resetAttribute='data-reset-'+namespace;
    host.innerHTML=`<h2 id="${id}">${esc(title)}</h2><p>Alege un răspuns; feedbackul explică imediat conceptul. Nu se păstrează un scor.</p>${items.map(([question,options],i)=>`<fieldset><legend>${i+1}. ${esc(question)}</legend>${options.map((label,k)=>`<label><input type="radio" name="${namespace}-${i}" value="${k}" data-question="${i}">${esc(label)}</label>`).join('')}<p class="lab-quiz-feedback" role="status" aria-live="polite"></p></fieldset>`).join('')}<button type="button" class="outline-button" ${resetAttribute}>Resetează checkpoint-ul</button>`;
    host.addEventListener('change',event=>{const input=event.target,item=items[Number(input.dataset.question)];if(!item)return;input.closest('fieldset').querySelector('.lab-quiz-feedback').textContent=(Number(input.value)===item[2]?'✓ Corect. ':'Încearcă din nou. ')+item[3];});
    host.querySelector('['+resetAttribute+']').addEventListener('click',()=>{host.querySelectorAll('input').forEach(n=>n.checked=false);host.querySelectorAll('.lab-quiz-feedback').forEach(n=>n.textContent='');});
  }
  function mountDemo(d,card,{draw,onChange=()=>{},alternate=s=>s,afterRender=()=>{},onReset=()=>{},compareMode='second'}={}){
    let state={...d.defaults,compare:false};
    function render(){const result=draw(d,state,d.id),visual=state.compare&&compareMode==='toggle'?draw(d,alternate({...state}),d.id+'-initial'):result;card.querySelector('.lab-map').innerHTML=visual.svg;card.querySelector('.lab-legend').innerHTML=(visual.legend||[]).map(v=>`<li>${v.color?`<i class="lab-swatch" aria-hidden="true" style="background:${esc(v.color)}"></i>`:''}${esc(v.label)}</li>`).join('');card.querySelector('.lab-status').textContent=visual.status;card.querySelector('.lab-dynamic').innerHTML=result.dynamic||'';
      for(const c of d.controls){const wrapper=card.querySelector(`[data-control="${c.key}"]`);if(c.when)wrapper.hidden=!(Array.isArray(c.when[1])?c.when[1].includes(state[c.when[0]]):state[c.when[0]]===c.when[1]);if(c.type==='placement'){wrapper.querySelectorAll('input').forEach(n=>n.checked=n.value===state[c.key]);continue;}const n=wrapper.querySelector('input,select');if(!n)continue;
        if(c.optionsFor){const options=c.optionsBy[state[c.optionsFor]];if(n.dataset.options!==state[c.optionsFor]){n.innerHTML=options.map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('');n.dataset.options=state[c.optionsFor];}}
        if(c.type==='checkbox')n.checked=state[c.key];else n.value=state[c.key];const output=wrapper.querySelector('output');if(output)output.textContent=c.key==='scale'?`1:${[5000000,1000000,100000,10000][state.scale].toLocaleString('ro-RO')}`:state[c.key]+(c.unit||'');
      }
      const compare=card.querySelector('.lab-compare');compare.hidden=!state.compare||compareMode==='toggle';if(state.compare&&compareMode==='second'){const other=alternate({...state});compare.innerHTML='<h4>Compară · aceleași geometrii</h4>'+draw(d,other,d.id+'-compare').svg;}else compare.innerHTML='';
      card.querySelector('[data-compare]')?.setAttribute('aria-pressed',String(state.compare));afterRender({...state},result,card);
    }
    const change=event=>{const n=event.target,key=n.dataset.key;if(!key||n.tagName==='BUTTON')return;state[key]=n.type==='checkbox'?n.checked:n.type==='range'?Number(n.value):n.value;onChange(state,key);render();};
    card.addEventListener('input',change);card.addEventListener('change',event=>{if(!['range','color'].includes(event.target.type))change(event);});
    const reset=()=>{state={...d.defaults,compare:false};onReset();render();};card.addEventListener('click',event=>{const b=event.target.closest('button');if(b?.hasAttribute('data-reset'))reset();else if(b?.hasAttribute('data-compare')){state.compare=!state.compare;render();}});render();return {getState:()=>({...state}),setState:patch=>{state={...state,...patch};render();},reset,render};
  }
  root.CARTO_LAB={esc,sourceLink,sources,compactSources,controls,shell,checkpoint,mountDemo};
})(window);
