(function(root){
  'use strict';
  const D=root.CARTO_LABELING,L=root.CARTO_LAB,E=root.CARTO_LABEL_ENGINE,{esc}=L,controllers=new Map();
  const sectionNames=[['label-intro','Introducere'],['label-text','Cum arată textul · format și lizibilitate'],['label-points','Unde este textul · puncte'],['label-lines','Unde este textul · linii'],['label-polygons','Unde este textul · poligoane'],['label-callouts','Unde este textul · callouts'],['label-conflict','Dacă este afișat · conflicte'],['label-priority','Dacă este afișat · prioritate'],['label-obstacles','Dacă este afișat · obstacole'],['label-scale','Dacă este afișat · scară'],['label-density','Dacă este afișat · densitate'],['label-data-defined','Atribute → etichetă']];
  const world=()=>root.CARTO_STYLING.polygons.map(p=>`<path d="${E.polyPath(p.geometry)}" class="lab-context"/>`).join('');
  const legend=[{label:'Principal · pătrat',color:'#ba6350'},{label:'Secundar · cerc',color:'#477ba7'},{label:'Local · romb',color:'#41866b'}];
  function complex(){return root.CARTO_STYLING.polygons.map((p,i)=>`<path d="${E.polyPath(p.geometry)}" fill="${['#78ad9b','#477ba7','#ba6350','#e9bf66','#8c69a2'][i]}" fill-opacity=".8" stroke="var(--line)"/>`).join('')+root.CARTO_STYLING.lines.slice(0,3).map(line=>`<path d="${line.points.map(([x,y],i)=>(i?'L':'M')+x+' '+y).join(' ')}" fill="none" stroke="var(--ink)" stroke-width="3"/>`).join('');}
  function resultScene(features,options){const result=E.solve(features,options);return {result,content:world()+features.map(E.point).join('')+result.accepted.map(p=>E.renderLabel(p)).join('')};}
  function polygonScene(s,prefix){let content='',notes=[];for(const poly of D.polygons){const g=poly.geometry,centroid=E.centroid(g);content+=`<path d="${E.polyPath(g)}" fill="var(--blue-soft)" stroke="var(--ink)" stroke-width="1.5"><title>${esc(poly.type)}</title></path>`;let p;
      if(s.mode==='centroid'){p=E.makeLabel(poly,poly.name,...centroid,{size:18});if(s.forceInside&&!E.inside(centroid,g))p=E.interiorLabel(poly);content+=`<path d="M${centroid[0]-4} ${centroid[1]}h8M${centroid[0]} ${centroid[1]-4}v8" class="lab-reference"/>`;}
      if(s.mode==='horizontal')p=E.interiorLabel(poly);
      if(s.mode==='free')p=E.interiorLabel(poly,E.polygonAngle(g));
      if(s.mode==='outside')p=E.makeLabel(poly,poly.name,...poly.outside,{size:18});
      if(['perimeter','curved'].includes(s.mode)){let ring=g.slice();const segments=ring.map((a,i)=>({index:i,length:Math.hypot(ring[(i+1)%ring.length][0]-a[0],ring[(i+1)%ring.length][1]-a[1])}));const longest=segments.sort((a,b)=>b.length-a.length)[0];let a=ring[longest.index],b=ring[(longest.index+1)%ring.length];if(b[0]<a[0]){ring.reverse();a=b;b=g[longest.index];}const segmentIndex=ring.findIndex(v=>v===a),lengths=ring.map((v,i)=>Math.hypot(ring[(i+1)%ring.length][0]-v[0],ring[(i+1)%ring.length][1]-v[1])),before=lengths.slice(0,segmentIndex).reduce((a,b)=>a+b,0),total=lengths.reduce((a,b)=>a+b,0),offset=before+lengths[segmentIndex]/2;
        if(s.mode==='perimeter'){const angle=E.readable(Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI);if(E.metrics(poly.name,18).width<=longest.length)p=E.makeLabel(poly,poly.name,(a[0]+b[0])/2,(a[1]+b[1])/2,{size:18,angle});}
        else if(E.metrics(poly.name,18).width<=longest.length){const pathId=prefix+'-ring-'+poly.id;content+=`<defs><path id="${pathId}" d="${E.polyPath(ring)}"/></defs><text data-curved-label="${poly.id}" font-family="system-ui, sans-serif" font-size="18" font-weight="600" fill="var(--ink)" stroke="var(--surface)" stroke-width="2" paint-order="stroke" dominant-baseline="central"><textPath href="#${pathId}" startOffset="${offset/total*100}%" text-anchor="middle">${esc(poly.name)}</textPath></text>`;notes.push(poly.type+': urmărește conturul');continue;}}
      if(p){content+=E.renderLabel(p);notes.push(poly.type+': '+(s.mode==='centroid'&&!E.inside([p.x,p.y],g)?'centroid în afara poligonului':'afișată'));}else notes.push(poly.type+': textul nu încape');
    }return {content,notes};
  }
  function draw(d,s,prefix){let content='',status='',dynamic='',currentLegend=[],result;
    if(['L0','L10','L11','L14'].includes(d.id)){
      const features=d.id==='L0'?D.dense.slice(0,18):d.id==='L11'?D.priority:D.dense;
      const options={avoid:!(['L0','L10'].includes(d.id)&&s.mode==='all'),limit:d.id==='L11'?3:d.id==='L14'?{low:4,medium:8,high:16}[s.density]:Infinity,priority:d.id==='L11'?p=>s[p.class]:p=>p.priority||0};
      const scene=resultScene(features,options);content=scene.content;result=scene.result;status=`${features.length} obiecte · ${result.accepted.length} etichete afișate · ${features.length-result.accepted.length} omise`;currentLegend=legend;dynamic=E.table(result.records);
    }else if(d.id==='L1'){
      const samples=D.points.slice(0,5).map((p,i)=>({...p,x:[130,340,130,340,240][i],y:[45,45,140,140,235][i]}));content=world()+samples.map(p=>E.point(p)+E.renderLabel(E.makeLabel(p,p.name,p.x,p.y+22,{size:Number(s.size),weight:Number(s.weight)}),{color:s.color,buffer:0})).join('');status=`5 etichete · ${s.size} px · greutate ${s.weight}`;
    }else if(['L2','L3','L4'].includes(d.id)){
      content=complex();if(d.id==='L4')content+=`<defs><filter id="${prefix}-shadow-effect" x="0" y="0" width="480" height="300" filterUnits="userSpaceOnUse"><feDropShadow dx="${s.strength/18}" dy="${s.strength/18}" stdDeviation="${s.strength/25}" flood-color="#000000" flood-opacity="${s.strength/100}"/></filter></defs>`;
      for(const [i,name] of ['Școala A','Parcul Nord','Spitalul B'].entries()){const p=E.makeLabel({id:i+1},name,[140,340,240][i],[80,175,245][i],{size:24});content+=E.renderLabel(p,{buffer:d.id==='L2'?s.buffer*4:0,background:d.id==='L3'?s.background:'none',padding:s.padding*4,opacity:s.opacity/100,filter:d.id==='L4'&&s.shadow?prefix+'-shadow-effect':''});}
      status=d.id==='L2'?`Buffer ${s.buffer} mm · conturul literelor`:d.id==='L3'?`Background ${s.background}`:`Shadow ${s.shadow?'activă · '+s.strength+'%':'oprită'}`;
    }else if(d.id==='L5'){
      const p=E.makeLabel({id:1},'Muzeul Civic',240,150,{size:25});const masks=`<defs><mask id="${prefix}-glyph-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="480" height="300"><rect width="480" height="300" fill="white"/><text x="240" y="150" text-anchor="middle" dominant-baseline="central" font-size="25" font-weight="600" font-family="system-ui, sans-serif" fill="black" stroke="black" stroke-width="12">Muzeul Civic</text></mask></defs>`;
      content=world()+masks+`<g ${s.mask?`mask="url(#${prefix}-glyph-mask)"`:''} data-mask-layer><path d="M35 165L440 130M50 105L430 205M220 35L250 270" fill="none" stroke="#477ba7" stroke-width="7"/>${E.point({id:'context',x:240,y:150,name:'Stație contextuală',class:'principal'})}</g>`+E.renderLabel(p,{buffer:0});status=s.mask?'Mask activă · simbolurile selectate sunt întrerupte':'Fără mask · simboluri peste zona textului';currentLegend=[{label:'Linii și simbol selectate pentru mask',color:'#477ba7'},{label:'Text fără buffer'}];
    }else if(d.id==='L6'){
      const features=D.points.slice(0,8).map((p,i)=>({...p,x:105+i%4*82,y:90+Math.floor(i/4)*130}));const scene=resultScene(features,{avoid:s.mode==='around',fixed:s.mode==='offset',distance:s.distance*4,preferred:s.position});content=scene.content;result=scene.result;status=`${s.mode==='around'?'Around Point':'Offset from Point'} · preferință ${s.position} · ${s.distance} mm · ${result.accepted.length}/8 etichete`;dynamic=E.table(result.records);
    }else if(d.id==='L7'){
      for(const line of D.lines){const id=prefix+'-path-'+line.id,info=E.pathInfo(line.path),offset=s.mode==='horizontal'?0:s.side==='above'?-16:s.side==='below'?16:0;content+=`<path id="${id}" d="${line.path}" fill="none" stroke="${line.color}" stroke-width="3" ${line.id==='rail'?'stroke-dasharray="10 5"':''}/>`;
        if(s.mode==='curved')content+=`<text data-curved-label="${line.id}" font-size="18" font-weight="600" font-family="system-ui, sans-serif" fill="var(--ink)" stroke="var(--surface)" stroke-width="2" paint-order="stroke" dominant-baseline="central" dy="${offset}"><textPath href="#${id}" startOffset="50%" text-anchor="middle">${esc(line.name)}</textPath></text>`;
        else content+=E.renderLabel(E.makeLabel(line,line.name,info.x,info.y+offset,{size:18,angle:s.mode==='parallel'?info.angle:0}));}
      status=`${s.mode} · ${s.mode==='horizontal'?'orizontal pe traseu':s.side} · 3 trasee`;
    }else if(d.id==='L8'){const scene=polygonScene(s,prefix);content=scene.content;status=`${s.mode} · 4 forme diferite`;dynamic='<ul>'+scene.notes.map(n=>'<li>'+esc(n)+'</li>').join('')+'</ul>';}
    else if(d.id==='L9'){
      const features=D.points.slice(0,3).map((p,i)=>({...p,id:i+1,x:[218,235,249][i],y:[138,153,135][i]})),positions={near:[[170,105],[270,180],[330,110]],spread:[[110,65],[130,255],[375,100]],top:[[90,55],[240,55],[390,55]]}[s.preset];const labels=features.map((p,i)=>E.makeLabel(p,p.id+' · '+p.name,...positions[i],{size:18}));content=world()+features.map(p=>E.point(p)+`<text x="${p.x}" y="${p.y+20}" class="lab-scene-text" text-anchor="middle">${p.id}</text>`).join('')+(s.callout?labels.map(E.callout).join(''):'')+labels.map(p=>E.renderLabel(p)).join('');status=`${s.preset} · callout ${s.callout?'activ':'oprit'} · 3 obiecte`;currentLegend=features.map(p=>({label:p.id+' · '+p.name}));
    }else if(d.id==='L12'){
      const features=D.points.slice(0,6).map((p,i)=>({...p,x:[110,270,290,340,205,230][i],y:[140,160,100,180,95,230][i]})),obstacles=[{x:155,y:115,width:110,height:80},{x:326,y:122,width:28,height:28}],scene=resultScene(features,{obstacles:s.obstacle?obstacles:[]});result=scene.result;content=world()+`<rect data-obstacle x="155" y="115" width="110" height="80" fill="var(--teal)" fill-opacity=".2" stroke="var(--teal)" stroke-dasharray="5 3"/><path data-obstacle d="M326 122L354 150M326 150L354 122" stroke="var(--ink)" stroke-width="5"/>`+features.map(E.point).join('')+result.accepted.map(p=>E.renderLabel(p)).join('');status=`Obstacole ${s.obstacle?'active':'oprite'} · ${result.accepted.length}/6 etichete`;dynamic=E.table(result.records);currentLegend=[{label:'Poligon și punct protejate · contur punctat / cruce',color:'var(--teal)'}];
    }else if(['L13','L15'].includes(d.id)){
      const level=Number(s.scale||0);let features=D.points,labels=[],records=[];
      if(d.id==='L13')features=D.points.filter((p,i)=>E.scaleVisible(p,level,{index:i,localCount:8}));
      for(const p of features){let text=p.name,size=18,angle=0,show=true;if(d.id==='L15'){if(s.property==='size')size=s.binding==='population'?12+p.population/10000*12:12+p.importance*2.4;if(s.property==='visibility')show=s.binding==='principal'?p.class==='principal':p.population>5000;if(s.property==='rotation')angle=E.readable(p.angle);if(s.property==='text'&&s.binding==='namePopulation')text=p.name+' · '+p.population;}
        const placement=show?E.makeLabel(p,text,p.x,p.y+23,{size,angle}):null;if(placement){labels.push(placement);}records.push({feature:p,placement,reason:show?'afișată':'condiție falsă'});}
      content=world()+D.points.map(E.point).join('')+labels.map(p=>E.renderLabel(p)).join('');currentLegend=legend;
      status=d.id==='L13'?`1:${[5000000,1000000,100000,10000][level].toLocaleString('ro-RO')} · ${labels.length}/10 etichete · font 18 px`:`${s.binding} → ${s.property} · ${labels.length}/10 etichete`;
      dynamic=d.id==='L15'?`<div class="lab-table-scroll"><table class="lab-data"><caption>Atribute fictive și rezultatul legăturii</caption><thead><tr><th scope="col">ID</th><th scope="col">population</th><th scope="col">angle</th><th scope="col">Etichetă</th></tr></thead><tbody>${records.map(r=>`<tr><th scope="row">${r.feature.id}</th><td>${r.feature.population}</td><td>${r.feature.angle}°</td><td>${esc(r.placement?.text||r.reason)}</td></tr>`).join('')}</tbody></table></div>`:'';
    }
    return {svg:E.frame(prefix,d.title,status,content),legend:currentLegend,status,dynamic};
  }
  function switchPanel(labeling,updateHash=false){for(const name of ['styling','labeling']){const active=(name==='labeling')===labeling,tab=document.getElementById(name+'-tab');tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;document.getElementById(name+'-panel').hidden=!active;}document.querySelector('.lesson-hero .lab-source-compact').href=labeling?'#qgis-label-sources':'#qgis-sources';if(updateHash)history.replaceState(null,'',labeling?'#etichetare':'#stilizare');}
  function hashPanel(){const id=decodeURIComponent(location.hash.slice(1)),target=document.getElementById(id);if(id==='etichetare'||target?.closest('#labeling-panel'))switchPanel(true);else if(id==='stilizare'||target?.closest('#styling-panel'))switchPanel(false);if(target)requestAnimationFrame(()=>target.scrollIntoView({block:'start',behavior:'instant'}));}
  function start(){const container=document.getElementById('labeling-root');if(!container)return;
    container.innerHTML=sectionNames.map(([id,title])=>`<section id="${id}" class="styling-section"><h2>${title}</h2>${D.demos.filter(d=>d.section===id).map(L.shell).join('')}</section>`).join('');
    const classic=document.getElementById('labeling-classic'),source=root.CARTO_CONTENT.source;
    document.getElementById('label-intro').after(classic);
    classic.querySelector('[data-classic-reference]').textContent=`${source.authors}, ${source.title}, ${source.year}.`;
    classic.querySelector('[data-classic-source-link]').innerHTML=`<a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer" aria-label="Vezi manualul în Biblioteca Digitală; se deschide într-o filă nouă">Vezi manualul în Biblioteca Digitală ↗</a>`;
    D.demos.forEach(d=>controllers.set(d.id,L.mountDemo(d,document.getElementById(d.id),{draw,onChange:(s,key)=>{if(d.id==='L15'&&key==='property')s.binding=d.controls.find(c=>c.key==='binding').optionsBy[s.property][0][0];},alternate:s=>{if(d.id==='L0')s.mode=s.mode==='all'?'controlled':'all';if(d.id==='L10')s.mode=s.mode==='all'?'avoid':'all';if(d.id==='L2')s.buffer=s.buffer===0?1:0;if(d.id==='L5')s.mask=!s.mask;return s;}})));
    L.checkpoint(document.getElementById('labeling-checkpoint'),D.quiz,{title:'Checkpoint · Etichetare',id:'label-checkpoint-title',namespace:'label-quiz'});
    document.getElementById('label-source-compact').innerHTML=L.compactSources(['label-settings','labels'],{target:'qgis-label-sources',subject:'etichetare'});document.getElementById('label-source-root').innerHTML=L.sources(['label-settings','labels'],{id:'qgis-label-sources',title:'Aplică etichetarea în QGIS'});
    for(const name of ['styling','labeling']){const tab=document.getElementById(name+'-tab');tab.addEventListener('click',()=>switchPanel(name==='labeling',true));tab.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?'styling':event.key==='End'?'labeling':name==='styling'?'labeling':'styling';switchPanel(next==='labeling',true);document.getElementById(next+'-tab').focus();});}
    addEventListener('hashchange',hashPanel);hashPanel();
  }
  start();
})(window);
