/* Separate practical maps for the historical representation methods. */
(function (root) {
  'use strict';
  const datasets = root.CARTO_METHOD_DATA;
  const methodToKey = {diagrams:'diagrams',choropleth:'choropleth',cartodiagram:'cartodiagram',signs:'signs',areas:'areas',qualitative:'qualitative',flows:'flows',isolines:'isolines',dots:'dots'};
  const colors = {domestic:'#4f83a5',industry:'#b98551',services:'#69a394',school:'#4f83a5',hospital:'#b65c58',library:'#8a75a7',station:'#b98551',forest:'#5e886d',meadow:'#a8b976',reeds:'#74a7a0',agriculture:'#d4b36b',built:'#ad8290',water:'#6fa9ca'};
  const labels = {domestic:'Consum domestic',industry:'Industrie',services:'Servicii',school:'Școală',hospital:'Spital',library:'Bibliotecă',station:'Gară',forest:'Pădure',meadow:'Pajiște',reeds:'Stufăriș',agriculture:'Agricol',built:'Construit',water:'Apă'};
  const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const polygon = points => points.map(([x,y])=>`${x},${y}`).join(' ');
  const frame = title => `<rect class="method-map-bg" x="10" y="10" width="500" height="400" rx="12"/><text class="method-map-heading" x="28" y="34">${esc(title)}</text>`;
  const swatch = (name,color,extra='') => `<span class="method-legend-item"><i style="background:${color}"></i>${esc(name)}${extra}</span>`;
  const piePath = (cx,cy,r,start,end) => {const xy=a=>[cx+r*Math.cos((a-90)*Math.PI/180),cy+r*Math.sin((a-90)*Math.PI/180)],a=xy(start),b=xy(end);return `M${cx} ${cy}L${a[0]} ${a[1]}A${r} ${r} 0 ${end-start>180?1:0} 1 ${b[0]} ${b[1]}Z`;};
  const pie = (cx,cy,r,values,palette,names) => {const total=values.reduce((sum,v)=>sum+v,0);let start=0;return values.map((value,i)=>{const end=start+value/total*360,shape=`<path d="${piePath(cx,cy,r,start,end)}" fill="${palette[i]}" stroke="var(--surface)" stroke-width="1"><title>${esc(names[i])}: ${value}</title></path>`;start=end;return shape;}).join('');};
  const controls = {
    diagrams:`<label>Diagramă<select id="method-chart"><option value="pie">Sectoare circulare</option><option value="bar">Bare</option></select></label>`,
    choropleth:`<label>Atribut<select id="method-attribute"><option value="density">Densitate (loc./km²)</option><option value="growth">Creștere (‰)</option></select></label><label for="method-classes">Clase <output id="method-classes-out">5</output><input id="method-classes" type="range" min="3" max="6" value="5"></label><label>Clasificare<select id="method-classification"><option value="equal">Interval egal</option><option value="quantile">Cuantile</option></select></label>`,
    cartodiagram:`<label for="method-size">Mărimea maximă <output id="method-size-out">34</output><input id="method-size" type="range" min="20" max="42" value="34"></label>`,
    signs:`<fieldset><legend>Categorii vizibile</legend><div class="method-toggle-list">${['school','hospital','library','station'].map(type=>`<button type="button" data-method-category="${type}" aria-pressed="true">${labels[type]}</button>`).join('')}</div></fieldset>`,
    areas:`<fieldset><legend>Vegetație vizibilă</legend><div class="method-toggle-list">${['forest','meadow','reeds'].map(type=>`<button type="button" data-method-category="${type}" aria-pressed="true">${labels[type]}</button>`).join('')}</div></fieldset>`,
    qualitative:`<p class="small">Întregul teritoriu este împărțit în categorii nominale; nici o celulă nu rămâne neclasificată.</p>`,
    flows:`<label><input id="method-direction" type="checkbox" checked> Afișează direcția</label><label><input id="method-weak" type="checkbox"> Ascunde fluxurile sub 15 mii</label><label for="method-flow-size">Grosime relativă <output id="method-flow-size-out">1,5×</output><input id="method-flow-size" type="range" min="1" max="3" step=".5" value="1.5"></label>`,
    isolines:`<label for="method-interval">Interval <output id="method-interval-out">4°C</output><input id="method-interval" type="range" min="2" max="6" step="2" value="4"></label><label><input id="method-points" type="checkbox" checked> Puncte de eșantionare</label><label><input id="method-surface" type="checkbox" checked> Suprafață colorată</label><label><input id="method-lines" type="checkbox" checked> Izolinii</label>`,
    dots:`<label>Un punct reprezintă<select id="method-dot-value"><option value="500">500 locuitori</option><option value="1000" selected>1.000 locuitori</option><option value="2000">2.000 locuitori</option></select></label>`
  };
  function markup(key) {
    const data=datasets[key];
    return `<section id="exploreaza" class="lesson-section"><div class="lesson-section-header"><div><span class="eyebrow">EXEMPLU CARTOGRAFIC DISTINCT</span><h2>${esc(data.title)}</h2></div><span class="source-tag qgis-tag">Date fictive</span></div><div class="interactive-card method-specific" data-method="${key}" data-dataset="${esc(data.id)}" data-filterable data-content-type="exemplu,qgis" data-level="essential" data-source="gis" data-theme="${key==='signs'?'simbolizare':'reprezentare'}"><div class="interactive-header"><h3>${esc(data.title)}</h3><span class="dataset-note">${esc(data.unit)} · set sintetic</span></div><div class="interactive-body"><div class="control-panel">${controls[key]}</div><div class="viz-panel"><svg id="method-specific-svg" class="method-map" viewBox="0 0 520 420" preserveAspectRatio="xMidYMid meet" role="img" aria-label="${esc(data.title)}"></svg></div><div class="result-panel"><h3>Legendă</h3><div id="method-specific-legend" class="method-legend"></div><p id="method-specific-note" class="small"></p></div></div></div></section>`;
  }
  function drawDiagrams(data) {
    const chart=document.querySelector('#method-chart').value, palette=[colors.domestic,colors.industry,colors.services];
    let svg=frame('Șase orașe · utilizarea apei');
    svg+=`<path class="method-context-line" d="M80 140Q150 180 260 100T440 170M110 290Q210 235 320 280T440 330"/>`;
    for(const city of data.cities){const vals=[city.domestic,city.industry,city.services];svg+=`<circle class="method-city-halo" cx="${city.x}" cy="${city.y}" r="33"/>`;if(chart==='pie')svg+=pie(city.x,city.y,24,vals,palette,['Consum domestic','Industrie','Servicii']);else vals.forEach((v,i)=>{const h=v/70*46;svg+=`<rect x="${city.x-24+i*17}" y="${city.y+19-h}" width="14" height="${h}" fill="${palette[i]}"><title>${labels[['domestic','industry','services'][i]]}: ${v} mii m³/zi</title></rect>`;});svg+=`<text class="method-map-label" x="${city.x}" y="${city.y+46}" text-anchor="middle">${esc(city.name)}</text>`;}
    return {svg,legend:['domestic','industry','services'].map(type=>swatch(labels[type],colors[type])).join(''),note:`Fiecare diagramă reprezintă trei valori în mii m³/zi pentru un oraș fictiv. Forma selectată: ${chart==='pie'?'sectoare':'bare'}.`};
  }
  function thresholds(values,count,mode){const sorted=[...values].sort((a,b)=>a-b),min=sorted[0],max=sorted.at(-1);return Array.from({length:count+1},(_,i)=>mode==='quantile'?sorted[Math.min(sorted.length-1,Math.floor(i*(sorted.length-1)/count))]:min+(max-min)*i/count);}
  function drawChoropleth(data){const attr=document.querySelector('#method-attribute').value,count=+document.querySelector('#method-classes').value,mode=document.querySelector('#method-classification').value,values=data.regions.map(r=>r[attr]),cuts=thresholds(values,count,mode),ramp=['#dceaf2','#a9cee0','#74abc7','#4b89ae','#2b648b','#174262'];document.querySelector('#method-classes-out').textContent=count;let svg=frame('Opt regiuni · variabilă numerică');for(const region of data.regions){const value=region[attr],index=Math.min(count-1,cuts.slice(1).findIndex((limit,i)=>i===count-1||value<limit));const center=region.polygon.reduce((sum,p)=>[sum[0]+p[0]/region.polygon.length,sum[1]+p[1]/region.polygon.length],[0,0]);svg+=`<polygon class="method-region" points="${polygon(region.polygon)}" fill="${ramp[index]}"><title>${esc(region.name)}: ${value} ${attr==='density'?'loc./km²':'‰'}</title></polygon><text class="method-map-label" x="${center[0]}" y="${center[1]}" text-anchor="middle">${esc(region.name)}</text>`;}const unit=attr==='density'?'loc./km²':'‰';return {svg,legend:Array.from({length:count},(_,i)=>swatch(`${Math.round(cuts[i])}–${Math.round(cuts[i+1])} ${unit}`,ramp[i])).join(''),note:`Atribut numeric: ${attr==='density'?'densitatea populației':'creșterea populației'}. ${count} clase, ${mode==='equal'?'intervale egale':'cuantile'}.`};}
  function drawCartodiagram(data){const maxSize=+document.querySelector('#method-size').value;document.querySelector('#method-size-out').textContent=maxSize;const maxTotal=Math.max(...data.regions.map(r=>r.solar+r.wind+r.hydro));let svg=frame('Provincii · producție energetică');for(const region of data.regions)svg+=`<polygon class="method-region method-subdued" points="${polygon(region.polygon)}"><title>${esc(region.name)}</title></polygon>`;for(const region of data.regions){const vals=[region.solar,region.wind,region.hydro],total=vals.reduce((a,b)=>a+b,0),r=Math.sqrt(total/maxTotal)*maxSize;svg+=pie(region.x,region.y,r,vals,['#d9a35c','#6fa8b7','#4e789e'],['Solar','Eolian','Hidro'])+`<text class="method-map-label" x="${region.x}" y="${region.y+r+14}" text-anchor="middle">${esc(region.name)}</text>`;}return {svg,legend:swatch('Solar','#d9a35c')+swatch('Eolian','#6fa8b7')+swatch('Hidro','#4e789e')+`<span class="method-legend-item">Aria diagramei ∝ total GWh/an</span>`,note:'Geografia de fundal este discretă; diagrama de deasupra fiecărei provincii prezintă structura și volumul producției.'};}
  function selectedCategories(){return new Set([...document.querySelectorAll('[data-method-category][aria-pressed="true"]')].map(el=>el.dataset.methodCategory));}
  function drawSigns(data){const selected=selectedCategories(),symbols={school:['rect','Ș'],hospital:['circle','+'],library:['diamond','B'],station:['triangle','G']};let svg=frame('Orașul Meridia · servicii publice');for(let x=54;x<=470;x+=57)svg+=`<path class="method-street" d="M${x} 52L${x-18} 385"/>`;for(let y=72;y<=370;y+=53)svg+=`<path class="method-street" d="M35 ${y}Q260 ${y+10} 485 ${y-4}"/>`;svg+=`<path class="method-park" d="M195 205Q228 173 279 196L299 254Q264 283 208 258Z"/>`;for(const place of data.services){if(!selected.has(place.type))continue;const [shape,glyph]=symbols[place.type],color=colors[place.type],x=place.x,y=place.y;let outline=shape==='circle'?`<circle cx="${x}" cy="${y}" r="12"/>`:shape==='diamond'?`<path d="M${x} ${y-13}L${x+13} ${y}L${x} ${y+13}L${x-13} ${y}Z"/>`:shape==='triangle'?`<path d="M${x} ${y-14}L${x+14} ${y+11}L${x-14} ${y+11}Z"/>`:`<rect x="${x-12}" y="${y-12}" width="24" height="24" rx="3"/>`;svg+=`<g class="method-service" fill="${color}" tabindex="0" role="img" aria-label="${esc(place.name)}, ${esc(labels[place.type])}">${outline}<text x="${x}" y="${y+4}" text-anchor="middle">${glyph}</text><title>${esc(place.name)}</title></g>`;}return {svg,legend:['school','hospital','library','station'].map(type=>swatch(labels[type],colors[type],selected.has(type)?'':' (ascuns)')).join(''),note:`${data.services.filter(p=>selected.has(p.type)).length} servicii vizibile. Simbolul indică un obiect punctual și are formă diferită pentru fiecare categorie.`};}
  function drawAreas(data){const selected=selectedCategories();let svg=frame('Arealuri de vegetație · întinderi naturale');svg+=`<path class="method-context-line" d="M40 220Q160 190 260 229T480 214M260 40Q240 170 278 390"/>`;for(const area of data.patches){if(!selected.has(area.type))continue;svg+=`<path class="method-area-patch" d="${area.path}" fill="${colors[area.type]}"><title>${esc(area.name)}</title></path>`;}return {svg,legend:['forest','meadow','reeds'].map(type=>swatch(labels[type],colors[type],selected.has(type)?'':' (ascuns)')).join(''),note:'Petele arată areale discontinue. Spațiile dintre ele rămân neclasificate; limitele nu urmează diviziuni administrative.'};}
  function drawQualitative(data){let svg=frame('Acoperire completă · utilizarea terenului');for(const cell of data.cells)svg+=`<polygon class="method-land-cell" points="${polygon(cell.polygon)}" fill="${colors[cell.type]}"><title>${esc(labels[cell.type])}</title></polygon>`;return {svg,legend:data.categories.map(type=>swatch(labels[type],colors[type])).join(''),note:'Cele nouă poligoane acoperă integral cadrul teritorial; fiecare loc aparține unei categorii nominale.'};}
  function drawFlows(data){const direction=document.querySelector('#method-direction').checked,hideWeak=document.querySelector('#method-weak').checked,width=+document.querySelector('#method-flow-size').value;document.querySelector('#method-flow-size-out').textContent=`${String(width).replace('.',',')}×`;const nodes=Object.fromEntries(data.nodes.map(node=>[node.id,node]));let svg=frame('Centre urbane · deplasări zilnice')+`<defs><marker id="flow-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" fill="var(--blue)"/></marker></defs>`;const visible=data.routes.filter(route=>!hideWeak||route.value>=15);for(const route of visible){const a=nodes[route.from],b=nodes[route.to],x1=a.x,y1=a.y,x2=b.x,y2=b.y,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),ux=dx/len,uy=dy/len,offset=19;svg+=`<path class="method-flow" d="M${(x1+ux*offset).toFixed(1)} ${(y1+uy*offset).toFixed(1)}L${(x2-ux*offset).toFixed(1)} ${(y2-uy*offset).toFixed(1)}" stroke-width="${(width*(1+route.value/12)).toFixed(1)}" ${direction?'marker-end="url(#flow-arrow)"':''}><title>${esc(a.name)} → ${esc(b.name)}: ${route.value} mii călătorii/zi</title></path>`;}for(const node of data.nodes)svg+=`<circle class="method-flow-node" cx="${node.x}" cy="${node.y}" r="15"/><text class="method-flow-letter" x="${node.x}" y="${node.y+4}" text-anchor="middle">${node.id}</text><text class="method-map-label" x="${node.x}" y="${node.y+32}" text-anchor="middle">${esc(node.name)}</text>`;return {svg,legend:swatch('Grosime ∝ călătorii / zi','var(--blue)')+`<span class="method-legend-item">${visible.length} din ${data.routes.length} fluxuri vizibile</span>`,note:`${visible.length} legături fictive afișate. ${direction?'Săgețile indică sensul deplasării.':'Sensul deplasării este ascuns.'} Grosimea este scalată la ${String(width).replace('.',',')}×.`};}
  function isolineSegments(field,level){const pieces=[],rows=field.length,cols=field[0].length,ox=55,oy=58,sx=410/(cols-1),sy=315/(rows-1);const edges=[[0,1],[1,2],[3,2],[0,3]],corners=[[0,0],[1,0],[1,1],[0,1]],table={1:[[3,0]],2:[[0,1]],3:[[3,1]],4:[[1,2]],5:[[3,2],[0,1]],6:[[0,2]],7:[[3,2]],8:[[2,3]],9:[[0,2]],10:[[0,3],[1,2]],11:[[1,2]],12:[[1,3]],13:[[0,1]],14:[[0,3]]};for(let y=0;y<rows-1;y++)for(let x=0;x<cols-1;x++){const values=[field[y][x],field[y][x+1],field[y+1][x+1],field[y+1][x]],code=values.reduce((sum,value,i)=>sum|(value>=level?1<<i:0),0);const point=edge=>{const [a,b]=edges[edge],t=(level-values[a])/(values[b]-values[a]),xx=x+corners[a][0]+(corners[b][0]-corners[a][0])*t,yy=y+corners[a][1]+(corners[b][1]-corners[a][1])*t;return [ox+xx*sx,oy+yy*sy];};for(const [a,b] of table[code]||[])pieces.push([point(a),point(b)]);}return pieces;}
  function drawIsolines(data){const interval=+document.querySelector('#method-interval').value,showPoints=document.querySelector('#method-points').checked,showSurface=document.querySelector('#method-surface').checked,showLines=document.querySelector('#method-lines').checked;document.querySelector('#method-interval-out').textContent=`${interval}°C`;let svg=frame('Câmp de temperatură · puncte și izoterme'),field=data.field,ox=55,oy=58,sx=410/6,sy=315/6;if(showSurface)for(let y=0;y<6;y++)for(let x=0;x<6;x++){const avg=(field[y][x]+field[y][x+1]+field[y+1][x]+field[y+1][x+1])/4,hue=210-(avg-5)*5;svg+=`<rect x="${ox+x*sx}" y="${oy+y*sy}" width="${sx+1}" height="${sy+1}" fill="hsl(${hue} 44% 75%)" opacity=".9"/>`;}else svg+=`<rect x="${ox}" y="${oy}" width="410" height="315" fill="var(--surface-alt)"/>`;if(showLines)for(let level=Math.ceil(5/interval)*interval;level<=26;level+=interval){const pieces=isolineSegments(field,level);for(const [[x1,y1],[x2,y2]] of pieces)svg+=`<line class="method-isoline" x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}"><title>${level}°C</title></line>`;if(pieces.length){const [x,y]=pieces[Math.floor(pieces.length/2)][0];svg+=`<text class="method-isoline-label" x="${x.toFixed(1)}" y="${y.toFixed(1)}">${level}°</text>`;}}if(showPoints)for(let y=0;y<7;y++)for(let x=0;x<7;x++)svg+=`<circle class="method-sample" cx="${ox+x*sx}" cy="${oy+y*sy}" r="3"><title>${field[y][x]}°C</title></circle>`;return {svg,legend:swatch('Temperatură mai mică','hsl(210 44% 75%)')+swatch('Temperatură mai mare','hsl(105 44% 75%)')+`<span class="method-legend-item">Interval: ${interval}°C</span>`,note:'Valorile din grila sintetică formează o suprafață numerică. Izoliniile unesc pozițiile interpolate cu aceeași temperatură.'};}
  function inside(point,polygon){let inside=false;const [x,y]=point;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const [xi,yi]=polygon[i],[xj,yj]=polygon[j];if((yi>y)!==(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)inside=!inside;}return inside;}
  function halton(index,base){let result=0,unit=1/base;while(index){result+=(index%base)*unit;index=Math.floor(index/base);unit/=base;}return result;}
  function dotPositions(polygon,count,seed){const xs=polygon.map(p=>p[0]),ys=polygon.map(p=>p[1]),left=Math.min(...xs),top=Math.min(...ys),width=Math.max(...xs)-left,height=Math.max(...ys)-top,points=[];for(let i=1;points.length<count&&i<2000;i++){const point=[left+halton(i+seed,2)*width,top+halton(i+seed,3)*height];if(inside(point,polygon))points.push(point);}return points;}
  function drawDots(data){const dotValue=+document.querySelector('#method-dot-value').value;let svg=frame('Districte rurale · populație statistică');for(const [index,district] of data.districts.entries()){svg+=`<polygon class="method-dot-district" points="${polygon(district.polygon)}"><title>${esc(district.name)}: ${district.population} locuitori</title></polygon>`;const count=Math.round(district.population/dotValue);for(const [x,y] of dotPositions(district.polygon,count,index*97))svg+=`<circle class="method-stat-dot" cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="3"/>`;const center=district.polygon.reduce((sum,p)=>[sum[0]+p[0]/district.polygon.length,sum[1]+p[1]/district.polygon.length],[0,0]);svg+=`<text class="method-map-label" x="${center[0]}" y="${center[1]}" text-anchor="middle">${esc(district.name)}</text>`;}return {svg,legend:swatch(`1 punct = ${dotValue.toLocaleString('ro-RO')} locuitori`,'var(--blue)'),note:'Punctele sunt plasate determinist în interiorul districtelor. Un punct reprezintă o cantitate, nu locul exact al unei persoane.'};}
  const renderers={diagrams:drawDiagrams,choropleth:drawChoropleth,cartodiagram:drawCartodiagram,signs:drawSigns,areas:drawAreas,qualitative:drawQualitative,flows:drawFlows,isolines:drawIsolines,dots:drawDots};
  function init(key){key=methodToKey[key];if(!key)return;const data=datasets[key],panel=document.querySelector('.method-specific'),draw=()=>{const result=renderers[key](data);panel.querySelector('#method-specific-svg').innerHTML=result.svg;panel.querySelector('#method-specific-legend').innerHTML=result.legend;panel.querySelector('#method-specific-note').textContent=result.note;};panel.addEventListener('input',event=>{if(event.target.matches('input,select'))draw();});panel.addEventListener('change',event=>{if(event.target.matches('input,select'))draw();});panel.addEventListener('click',event=>{const button=event.target.closest('[data-method-category]');if(!button)return;button.setAttribute('aria-pressed',String(button.getAttribute('aria-pressed')!=='true'));draw();});draw();}
  root.CARTO_METHODS={markup,init};
})(window);
