(function(root){
  'use strict';
  const data=root.CARTO_STYLING,L=root.CARTO_LAB,{esc}=L,states=new Map();
  const catColors=['#3276a3','#ba6350','#41866b','#8c69a2','#a27624'],shapes=['circle','square','triangle','diamond','cross'];
  const categories={A:'A · Școli',B:'B · Spitale',C:'C · Stații',D:'D · Biblioteci',E:'E · Centre civice'};
  const ramps={blue:['#e1eff7','#a6cbdc','#6fa9c6','#4586af','#2d6795','#234b76','#19344e'],green:['#e6f0db','#bad8a2','#8fbb79','#64a264','#44834e','#2c653c','#19472d'],purple:['#eee7f4','#d0bde1','#b297cd','#9372b6','#765395','#593c78','#3d2855']};
  const polyPath=g=>g.map(([x,y],i)=>`${i?'L':'M'}${x},${y}`).join(' ')+'Z';
  function centroid(vertices){let sum=0,x=0,y=0;vertices.forEach((a,i)=>{const b=vertices[(i+1)%vertices.length],cross=a[0]*b[1]-b[0]*a[1];sum+=cross;x+=(a[0]+b[0])*cross;y+=(a[1]+b[1])*cross;});return [x/(3*sum),y/(3*sum)];}
  const linePath=g=>g.map(([x,y],i)=>`${i?'L':'M'}${x},${y}`).join(' ');
  function marker(shape,x,y,size,fill,stroke='var(--ink)',width=1,rotation=0,opacity=1){
    const r=size/2,attr=`fill="${fill}" stroke="${stroke}" stroke-width="${width}"`;
    const drawing=shape==='square'?`<rect x="${-r}" y="${-r}" width="${size}" height="${size}" ${attr}/>`:shape==='triangle'?`<path d="M0 ${-r}L${r} ${r}L${-r} ${r}Z" ${attr}/>`:shape==='diamond'?`<path d="M0 ${-r}L${r} 0L0 ${r}L${-r} 0Z" ${attr}/>`:shape==='cross'?`<path d="M${-r} ${-r*.35}H${-r*.35}V${-r}H${r*.35}V${-r*.35}H${r}V${r*.35}H${r*.35}V${r}H${-r*.35}V${r*.35}H${-r}Z" ${attr}/>`:`<circle r="${r}" ${attr}/>`;
    return `<g transform="translate(${x} ${y}) rotate(${rotation})" opacity="${opacity}">${drawing}</g>`;
  }
  const pointTag=(p,text=p.id)=>`<text x="${p.x+12}" y="${p.y-13}" class="lab-scene-text">${esc(text)}</text>`;
  const context=()=>data.polygons.map(p=>`<path d="${polyPath(p.geometry)}" class="lab-context"/>`).join('');
  const frame=(id,title,description,content)=>`<svg viewBox="0 0 480 300" role="img" aria-labelledby="${id}-svg-title ${id}-svg-desc"><title id="${id}-svg-title">${esc(title)}</title><desc id="${id}-svg-desc">${esc(description)}. Date fictive, originale. Numerele identifică obiectele; explicațiile și valorile sunt disponibile și în text.</desc>${content}</svg>`;
  const item=(label,color)=>({label,color});
  const categoryLegend=()=>Object.entries(categories).map(([key,label],i)=>item(label,catColors[i]));
  function table(points){return `<div class="lab-table-scroll"><table class="lab-data"><caption>Atribute sintetice · geometria rămâne neschimbată</caption><thead><tr><th scope="col">ID</th><th scope="col">Tip</th><th scope="col">Valoare</th><th scope="col">Status</th></tr></thead><tbody>${points.map(p=>`<tr><th scope="row">${p.id}</th><td>${p.type}</td><td>${p.value}</td><td>${p.status}</td></tr>`).join('')}</tbody></table></div>`;}
  function graduation(n,ramp){const min=12,max=98,step=(max-min)/n,colors=Array.from({length:n},(_,i)=>ramps[ramp][Math.round(i*6/(n-1))]);return {colors,legend:colors.map((c,i)=>item(`${i+1}: ${+(min+i*step).toFixed(1)} ${i===n-1?'≤ v ≤':'≤ v <'} ${+(min+(i+1)*step).toFixed(1)}`,c)),classOf:v=>Math.min(n-1,Math.floor((v-min)/step))};}
  function polyScene(mode,s){const grad=graduation(Number(s.classes||5),s.ramp||'blue');return data.polygons.map((p,i)=>{let color=mode==='categorized'?catColors[i]:mode==='graduated'?grad.colors[grad.classOf(p.value)]:mode==='rule'&&p.value>=70?'#ba6350':'#84a8bb';return `<path d="${polyPath(p.geometry)}" fill="${color}" stroke="var(--ink)" stroke-width="1.2"/>${mode==='categorized'?`<path d="${polyPath(p.geometry)}" fill="url(#${s.prefix}-pattern-${i})"/>`:''}<text x="${p.geometry.reduce((sum,v)=>sum+v[0],0)/p.geometry.length}" y="${p.geometry.reduce((sum,v)=>sum+v[1],0)/p.geometry.length}" text-anchor="middle" fill="#162f3d" font-size="18" font-weight="700" stroke="#ffffff" stroke-width="3" paint-order="stroke">${p.type} · ${p.value}</text>`;}).join('');}
  function crossing(s){const roads=[{points:[[50,150],[430,150]],major:true},{points:[[230,40],[250,260]],major:false},{points:[[55,245],[410,60]],major:false}];const stroke=(r,outer)=>`<path d="${linePath(r.points)}" fill="none" stroke="${outer?'#28485e':r.major?'#e9bf66':'#dce5e9'}" stroke-width="${outer?20:12}" stroke-linecap="round"/>`;return s.order==='good'?roads.map(r=>stroke(r,true)).join('')+[...roads.filter(r=>!r.major),roads[0]].map(r=>stroke(r,false)).join(''):roads.map(r=>stroke(r,true)+stroke(r,false)).join('');}
  function repeated(line,s){let remaining=Number(s.spacing)/2,out='';for(let k=1;k<line.length;k++){const a=line[k-1],b=line[k],dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI;while(remaining<len){const x=a[0]+dx*remaining/len,y=a[1]+dy*remaining/len;out+=s.mode==='hash'?`<g transform="translate(${x} ${y}) rotate(${angle+Number(s.angle)})"><line x1="${-s.length/2}" x2="${s.length/2}" stroke="var(--ink)" stroke-width="2"/></g>`:marker('triangle',x,y,s.size,'#ba6350','var(--ink)',1,angle+90);remaining+=Number(s.spacing);}remaining-=len;}return out;}
  function lineOffset(points,offset){return points.map(([x,y],i)=>{const a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)],dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1;return [x-dy/len*offset,y+dx/len*offset];});}
  function draw(d,s){let content='',legend=[],status='',dynamic='';const id=d.id,prefix=id+(s.comparison?'-compare':'');
    if(['S0','S1','S2','S3','S12'].includes(id)){
      content=context();const points=id==='S3'?data.points.slice(0,6):data.points;
      for(const p of points){let symbol='';
        if(id==='S0'){const index=p.type.charCodeAt(0)-65;symbol=marker(s.mode==='categorized'?shapes[index]:'circle',p.x,p.y,s.mode==='proportional'?Math.sqrt(p.value)*3:18,s.mode==='categorized'?catColors[index]:s.mode==='rule'&&p.value>=70?'#ba6350':'#477ba7','var(--ink)',s.mode==='rule'&&p.value>=70?3:1);}
        if(id==='S1'){content+=`<path d="M${p.x-5} ${p.y}h10M${p.x} ${p.y-5}v10" class="lab-reference"/>`;symbol=marker(s.shape,p.x+Number(s.offsetX)*4,p.y+Number(s.offsetY)*4,Number(s.size)*4,s.fill,s.outline?s.stroke:'none',Number(s.strokeWidth)*4,s.rotation);}
        if(id==='S2')symbol=s.type==='font'?`<text x="${p.x}" y="${p.y+9}" fill="#477ba7" stroke="var(--ink)" stroke-width=".4" text-anchor="middle" font-size="28" font-weight="700" font-family="system-ui,sans-serif">H</text>`:marker(s.type==='svg'?'cross':'circle',p.x,p.y,24,'#477ba7');
        if(id==='S3')symbol=marker('circle',p.x,p.y,(s.mode==='value'?Math.sqrt(p.value)*3:18)*Number(s.factor),'#477ba7');
        if(id==='S12'){symbol=marker('circle',p.x,p.y,5,'var(--muted)','none');if(s.high&&p.value>=70)symbol+=marker('circle',p.x,p.y,36,'none','#ba6350',3);if(s.typeA&&p.type==='A')symbol+=marker('diamond',p.x,p.y,26,'#d4b061');if(s.active&&p.status==='active')symbol+=marker('cross',p.x,p.y,14,'#41866b');}
        content+=`<g data-feature-id="${p.id}"><title>ID ${p.id}: ${p.type}, value ${p.value}, ${p.status}</title>${symbol}</g>`+pointTag(p,id==='S3'&&s.values?p.value:p.id);
      }
      if(id==='S0'){legend=s.mode==='categorized'?categoryLegend():s.mode==='rule'?[item('value ≥ 70 · cerc cu contur gros','#ba6350'),item('alte valori · cerc simplu','#477ba7')]:[item(s.mode==='proportional'?'Aria simbolului ∝ value':'Același simbol pentru toate obiectele','#477ba7')];status=`10 puncte · aceleași ID-uri, coordonate și valori · ${s.mode}`;dynamic=table(points);}
      if(id==='S1')status=`${s.shape} · ${s.size} mm · offset (${s.offsetX}, ${s.offsetY}) mm · ${s.outline?'contur activ':'fără contur'}`;
      if(id==='S2')status=s.type==='font'?'Font-like · H în fontul sistemului':s.type==='svg'?'SVG-like · cruce vectorială originală':'Simple Marker · cerc';
      if(id==='S3'){legend=[item(s.mode==='fixed'?'Dimensiune fixă':'Arie proporțională cu value','#477ba7')];status=`6 puncte · factor ${s.factor} · ${s.mode==='value'?'după valoare':'fix'}`;}
      if(id==='S12'){legend=[...(s.high?[item('Cerc mare · value ≥ 70','#ba6350')]:[]),...(s.typeA?[item('Romb · type A','#d4b061')]:[]),...(s.active?[item('Cruce · active','#41866b')]:[])];status=`${[s.high,s.typeA,s.active].filter(Boolean).length} reguli active · suprapunerile sunt permise`;dynamic=table(points);}
    }else if(id==='S4'){
      content=data.lines.map((line,i)=>`<path d="${linePath(line.points)}" class="lab-reference" stroke-dasharray="2 4"/><path d="${linePath(lineOffset(line.points,Number(s.offset)*4))}" fill="none" stroke="${s.color}" stroke-width="${s.width*4}" opacity="${s.opacity/100}" stroke-dasharray="${s.dash==='dash'?'14 8':s.dash==='dot'?'2 7':'none'}" stroke-linecap="round"/><text x="30" y="${line.points[0][1]-14}" class="lab-scene-text">${line.name}</text>`).join('');legend=[item('Linie fină punctată: geometria originală','var(--muted)'),item('Desenul stilizat',s.color)];status=`${s.width} mm · ${s.opacity}% · offset ${s.offset} mm`;
    }else if(id==='S5'){const roads=data.lines.slice(0,3);content=roads.map(line=>`${s.outer?`<path d="${linePath(line.points)}" fill="none" stroke="${s.outerColor}" stroke-width="${s.outerWidth*4}"/>`:''}${s.inner?`<path d="${linePath(line.points)}" fill="none" stroke="${s.innerColor}" stroke-width="${s.innerWidth*4}"/>`:''}`).join('');legend=[...(s.outer?[item('Outer casing · desenat primul',s.outerColor)]:[]),...(s.inner?[item('Inner stroke · desenat deasupra',s.innerColor)]:[])];status=`Road → ${s.outer?'Outer casing':'Exterior oprit'} + ${s.inner?'Inner stroke':'Interior oprit'}`;}
    else if(id==='S6'){content=data.lines.slice(0,3).map(line=>`<path d="${linePath(line.points)}" fill="none" stroke="var(--muted)" stroke-width="2"/>${repeated(line.points,s)}`).join('');status=`${s.mode==='marker'?'Marker Line':'Hashed Line'} · distanță ${s.spacing}`;legend=[item(s.mode==='marker'?'Triunghiuri orientate după tangentă':'Liniuțe înclinate față de tangentă',s.mode==='marker'?'#ba6350':'var(--ink)')];}
    else if(id==='S7'){content=data.polygons.map(p=>`<path d="${polyPath(p.geometry)}" fill="${s.fill}" fill-opacity="${s.opacity/100}" stroke="${s.outline?s.stroke:'none'}" stroke-width="${s.width*4}"/><text x="${p.geometry[0][0]+25}" y="${p.geometry[0][1]+38}" class="lab-scene-text">${p.type}</text>`).join('');status=`5 poligoane · umplere ${s.opacity}% · contur ${s.outline?s.width+' mm':'oprit'}`;legend=[item('Aceeași umplere pentru cinci geometrii',s.fill)];}
    else if(id==='S8'){
      const spacing=Number(s.spacing),pattern=`<pattern id="${prefix}-texture" width="${spacing}" height="${spacing}" patternUnits="userSpaceOnUse" patternTransform="rotate(${s.type==='line'?s.angle:0})">${s.type==='line'?`<line x1="0" x2="0" y2="${spacing}" stroke="${s.fill}" stroke-width="2"/>`:`<circle cx="${spacing/2}" cy="${spacing/2}" r="${s.size/2}" fill="${s.fill}"/>`}</pattern>`;
      content=`<defs>${pattern}<linearGradient id="${prefix}-gradient"><stop stop-color="${s.fill}"/><stop offset="1" stop-color="${s.end}"/></linearGradient></defs>`+data.polygons.map(p=>{const fill=s.type==='centroid'?'var(--surface)':s.type==='simple'?s.fill:`url(#${prefix}-${s.type==='gradient'?'gradient':'texture'})`;const centre=centroid(p.geometry);return `<path d="${polyPath(p.geometry)}" fill="${fill}" stroke="var(--ink)" stroke-width="1.5"/>${s.type==='centroid'?marker('circle',...centre,s.size*3,s.fill):''}`;}).join('');status=`Fill: ${s.type} · numai controalele relevante sunt vizibile`;
    }else if(['S9','S10','S11'].includes(id)){
      const mode=id==='S9'?s.mode:id==='S10'?(s.classify?'categorized':'single'):'graduated';const fieldTypes=s.field==='use'?['Parc','Locuire','Educație','Servicii','Transport']:Object.values(categories);
      const patterns=Array.from({length:5},(_,i)=>`<pattern id="${prefix}-pattern-${i}" width="${8+i*3}" height="${8+i*3}" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="${i%2?1.5:0}" fill="#152d3c"/><path d="M0 0L${8+i*3} ${i%2?0:8+i*3}" stroke="#152d3c" stroke-width=".6"/></pattern>`).join('');content=`<defs>${patterns}</defs>`+polyScene(mode,{...s,prefix});
      legend=mode==='categorized'?fieldTypes.map((label,i)=>item(label,catColors[i])):mode==='graduated'?graduation(Number(s.classes||5),s.ramp||'blue').legend:mode==='rule'?[item('value ≥ 70','#ba6350'),item('Celelalte valori','#84a8bb')]:[item('Single Symbol','#84a8bb')];
      status=id==='S10'?(s.classify?'Categorized · 5 categorii generate':'Single Symbol · apasă Classify'):mode==='graduated'?`Graduated · ${s.classes||5} clase · interval egal`:mode;
      if(id==='S9'){const explanations={single:['fără atribut','Unde sunt obiectele?','Toate cartierele au același simbol.'],categorized:['categorie nominală','Ce tip are fiecare obiect?','Cartiere A–E, diferențiate prin culoare și tipar.'],graduated:['valoare numerică','În ce interval se află valoarea?','Valori fictive 12–98, împărțite în cinci intervale.'],rule:['condiție / expresie','Ce obiecte satisfac condiția?','value ≥ 70: evidențiază suprafețele care trec pragul.']};const [attribute,question,example]=explanations[mode];dynamic=`<p><strong>Câmp → proprietate:</strong> ${mode==='single'?'fără câmp → același simbol':mode==='categorized'?'type → culoare și tipar':mode==='graduated'?'value → intensitatea culorii':'value ≥ 70 → evidențiere'}</p><p><strong>Tip de atribut:</strong> ${attribute}</p><p><strong>Întrebare:</strong> ${question}</p><p><strong>Exemplu:</strong> ${example}</p>`;}
    }else if(id==='S13'){
      const parts={outer:marker('circle',240,150,145,'#28485e','var(--ink)',3),inner:marker('circle',240,150,126,'#edf5f6','none'),cross:marker('cross',240,150,90,'#ba6350','none')};content=s.order.slice().reverse().filter(key=>s.enabled[key]).map(key=>parts[key]).join('');status='Deasupra → '+s.order.filter(key=>s.enabled[key]).map(key=>({outer:'Outer circle',inner:'Inner fill',cross:'Cross'}[key])).join(' → ')+' → dedesubt';
    }else if(id==='S14'){content=crossing(s);status=s.order==='good'?'Ordine controlată · casing-urile precedă interioarele':'Ordine nepotrivită · simboluri complete, unul peste altul';legend=[item('Drum principal','#e9bf66'),item('Drum secundar','#dce5e9')];}
    else if(id==='S15'){
      const values=data.points.map(p=>p[s.field]),min=Math.min(...values),max=Math.max(...values),normalized=p=>(p[s.field]-min)/(max-min||1);
      content=s.property==='width'?data.lines.map((line,i)=>{const p={...data.points[i],importance:line.importance};return `<path d="${linePath(line.points)}" fill="none" stroke="#477ba7" stroke-width="${2+normalized(p)*13}"/><text x="35" y="${line.points[0][1]-15}" class="lab-scene-text">${s.field}: ${p[s.field]}</text>`;}).join(''):context()+data.points.map(p=>marker('triangle',p.x,p.y,s.property==='size'?10+normalized(p)*28:24,'#477ba7','var(--ink)',1,s.property==='rotation'?p[s.field]:0,s.property==='opacity'?Math.max(.1,Math.min(1,p[s.field]/100)):1)+pointTag(p,p[s.field])).join('');status=`${s.field} → ${s.property}`;dynamic=`<p>${s.property==='rotation'?'La rotație, câmpul este interpretat în grade.':s.property==='opacity'?'La opacitate, câmpul este interpretat ca procent și limitat la 10–100%.':s.property==='size'?'Dimensiunile sunt scalate monoton între 10 și 38 unități vizuale; acesta nu este presetul de arie proporțională din S3.':'Grosimea este scalată între 2 și 15 unități vizuale.'} Valorile folosite sunt scrise lângă obiecte.</p>`;
    }else if(id==='S16'){const level=Number(s.scale);content=context()+data.lines.filter(line=>line.type==='principal'||line.type==='river'||(line.type==='secondary'&&level>=1)||(line.type==='local'&&level>=2)||(line.type==='rail'&&level>=1)).map(line=>`<path d="${linePath(line.points)}" fill="none" stroke="${line.type==='river'?'#3276a3':'var(--ink)'}" stroke-width="${line.type==='principal'?6:2}"/>`).join('')+data.points.filter((p,i)=>i<2||level>=3).map(p=>marker(p.id<3?'square':'circle',p.x,p.y,p.id<3?18:12,'#ba6350')+pointTag(p)).join('');status=`1:${[5000000,1000000,100000,10000][level].toLocaleString('ro-RO')} · ${level>=3?'10':'2'} puncte vizibile`;legend=[item('Context principal: vizibil permanent','var(--ink)'),item('Detaliu: dependent de scară','#ba6350')];}
    return {svg:frame(prefix,d.title,status||d.observation,content),legend,status,dynamic};
  }
  function render(d,card){const s=states.get(d.id),result=draw(d,s);card.querySelector('.lab-map').innerHTML=result.svg;card.querySelector('.lab-legend').innerHTML=result.legend.map(v=>`<li><i class="lab-swatch" aria-hidden="true" style="background:${v.color}"></i>${esc(v.label)}</li>`).join('');card.querySelector('.lab-status').textContent=result.status;card.querySelector('.lab-dynamic').innerHTML=result.dynamic;
    for(const control of d.controls){const wrapper=card.querySelector(`[data-control="${control.key}"]`),node=wrapper.querySelector('input,select');if(control.when)wrapper.hidden=!(Array.isArray(control.when[1])?control.when[1].includes(s[control.when[0]]):s[control.when[0]]===control.when[1]);if(node){if(control.type==='checkbox')node.checked=s[control.key];else node.value=s[control.key];const output=wrapper.querySelector('output');if(output)output.textContent=d.id==='S16'?`1:${[5000000,1000000,100000,10000][s.scale].toLocaleString('ro-RO')}`:`${s[control.key]}${control.unit||''}`;}}
    if(d.id==='S13')tree(card,s);
    if(d.id==='S5')card.querySelector('.lab-extra').innerHTML='<div class="lab-tree"><h4>Symbol Layer Tree · Road</h4><ol><li>Inner stroke · deasupra · '+(s.inner?'activ':'oprit')+'</li><li>Outer casing · dedesubt · '+(s.outer?'activ':'oprit')+'</li></ol><p class="small">Activează straturile cu cele două controale de mai sus.</p></div>';
    const compare=card.querySelector('.lab-compare');compare.hidden=!s.compare;if(s.compare){const baseline={...d.defaults,comparison:true};if(d.id==='S14')baseline.order=s.order==='bad'?'good':'bad';if(d.id==='S7'){baseline.width=s.width>1?.5:3;baseline.balance=s.width>1?'balanced':'dominant';}if(d.id==='S16')baseline.scale=s.scale===0?3:0;if(d.id==='S5'){baseline.outer=false;baseline.inner=true;}compare.innerHTML='<h4>Variante de comparat · aceleași geometrii</h4>'+draw(d,baseline).svg;}
    card.querySelector('[data-compare]')?.setAttribute('aria-pressed',String(!!s.compare));
  }
  function tree(card,s){const names={outer:'Outer circle',inner:'Inner fill',cross:'Cross'};card.querySelector('.lab-extra').innerHTML=`<fieldset class="lab-tree"><legend>Hospital · deasupra → dedesubt</legend>${s.order.map((key,i)=>`<div class="lab-tree-row"><label><input type="checkbox" data-layer="${key}" ${s.enabled[key]?'checked':''}>${names[key]}</label><button type="button" data-move="${key}" data-direction="-1" aria-label="Mută ${names[key]} în sus" ${i===0?'disabled':''}>↑</button><button type="button" data-move="${key}" data-direction="1" aria-label="Mută ${names[key]} în jos" ${i===s.order.length-1?'disabled':''}>↓</button></div>`).join('')}</fieldset>`;}
  function initial(d){return {...d.defaults,compare:false,...(d.id==='S13'?{order:['cross','inner','outer'],enabled:{outer:true,inner:true,cross:true}}:{})};}
  function initDemo(d,card){states.set(d.id,initial(d));const change=event=>{const target=event.target,key=target.dataset.key;if(!key&&!target.dataset.layer)return;const s=states.get(d.id);if(target.dataset.layer){s.enabled[target.dataset.layer]=target.checked;const layer=target.dataset.layer;render(d,card);card.querySelector(`[data-layer="${layer}"]`).focus();return;}if(target.tagName==='BUTTON')return;s[key]=target.type==='checkbox'?target.checked:target.type==='range'?Number(target.value):target.value;
      if(d.id==='S7'&&key==='balance')s.width=s.balance==='dominant'?3:.5;
      if(d.id==='S7'&&key==='width')s.balance=s.width>1?'dominant':'balanced';
      if(d.id==='S10'&&key==='field')s.classify=false;
      if(d.id==='S15'&&key==='property')s.field={size:'value',rotation:'angle',opacity:'confidence',width:'importance'}[s.property];
      render(d,card);
    };card.addEventListener('input',change);card.addEventListener('change',event=>{if(event.target.type!=='range'&&event.target.type!=='color')change(event);});
    card.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;let s=states.get(d.id);if(b.hasAttribute('data-reset')){states.set(d.id,initial(d));render(d,card);}else if(b.hasAttribute('data-compare')){s.compare=!s.compare;render(d,card);}else if(b.dataset.key==='classify'){s.classify=true;render(d,card);}else if(b.dataset.move){const key=b.dataset.move,i=s.order.indexOf(key),next=i+Number(b.dataset.direction);if(next<0||next>=s.order.length)return;[s.order[i],s.order[next]]=[s.order[next],s.order[i]];render(d,card);const after=card.querySelector(`[data-move="${key}"][data-direction="${b.dataset.direction}"]`);(after.disabled?card.querySelector(`[data-layer="${key}"]`):after).focus();}});render(d,card);
  }
  function mini(type){let content='';if(type==='cluster')content=marker('circle',120,50,50,'#477ba7')+'<text x="120" y="57" text-anchor="middle" fill="white" font-size="20">8</text>';if(type==='displacement')content=[0,1,2,3,4,5].map(i=>{const a=i*Math.PI/3,x=120+35*Math.cos(a),y=50+35*Math.sin(a);return `<line x1="120" y1="50" x2="${x}" y2="${y}" stroke="var(--muted)"/>`+marker(shapes[i%5],x,y,14,catColors[i%5]);}).join('');if(type==='heatmap')content='<defs><radialGradient id="advanced-heat"><stop stop-color="#ba6350"/><stop offset="1" stop-color="#e9bf66" stop-opacity="0"/></radialGradient></defs><ellipse cx="115" cy="50" rx="80" ry="45" fill="url(#advanced-heat)"/>';if(type==='inverted')content='<path d="M15 10H225V90H15Z M85 25V75H155V25Z" fill="#477ba7" fill-rule="evenodd"/>';if(type==='merged')content='<path d="M35 75V25H125V45H205V75Z" fill="#78ad9b" stroke="var(--ink)" stroke-width="2"/>';if(type==='2d')content='<path d="M80 70L140 70L180 45L180 20L140 45L80 45Z" fill="#477ba7" stroke="var(--ink)"/><path d="M80 45L120 20H180L140 45Z" fill="#78ad9b" stroke="var(--ink)"/>';return `<svg viewBox="0 0 240 100" role="img" aria-label="Schemă conceptuală originală: ${esc(type)}">${content}</svg>`;}
  function preview(){const container=document.querySelector('#lab-preview');const good=container.querySelector('input[value=good]').checked;const content=data.polygons.map((p,i)=>`<path d="${polyPath(p.geometry)}" fill="${good?'var(--surface)':catColors[i]}" stroke="${good?'var(--line)':'#28485e'}" stroke-width="${good?1:8}"/>`).join('')+data.lines.slice(0,4).map((line,i)=>`<path d="${linePath(line.points)}" fill="none" stroke="${good?(i===0?'var(--ink)':'var(--muted)'):catColors[i]}" stroke-width="${good?(i===0?5:2):9}"/>`).join('')+data.points.map(p=>marker('circle',p.x,p.y,good?18:46,good?'#ba6350':catColors[p.id%5])).join('');container.querySelector('.lab-preview-map').innerHTML=frame('preview','Ierarhie vizuală',good?'Tema principală este lizibilă; context subordonat':'Simboluri mari și contururi dominante concurează pentru atenție',content);container.querySelector('[role=status]').textContent=good?'Îmbunătățită: punctele sunt tema; contextul este subordonat.':'Slabă: toate elementele au intensitate mare, iar distribuția punctelor este greu de citit.';}
  function start(){const rootElement=document.querySelector('#styling-root');if(!rootElement)return;const sections=[['introducere','Introducere'],['puncte','Puncte'],['linii','Linii'],['poligoane','Poligoane'],['renderere','Renderere'],['symbol-layers','Straturi ale simbolului'],['data-defined','Proprietăți controlate de date'],['scara','Scară']];rootElement.innerHTML=sections.map(([id,title])=>`<section class="styling-section" id="${id}"><h2>${title}</h2>${data.demos.filter(d=>d.section===id).map(L.shell).join('')}${id==='renderere'?`<h3>Explorează rendererele avansate în QGIS</h3><p>Inventar ghidat · scheme conceptuale, nu simulări complete ale rendererelor.</p><div class="lab-advanced-grid">${data.advanced.map(([type,name,description,use])=>`<article><h4>${name}</h4>${mini(type)}<p>${description}</p><p><strong>Când este util?</strong> ${use}</p></article>`).join('')}</div><p>${L.sourceLink('vector-styling')}</p>`:''}</section>`).join('');data.demos.forEach(d=>initDemo(d,document.getElementById(d.id)));
    L.checkpoint(document.querySelector('#styling-checkpoint'),data.quiz);
    document.querySelector('#lab-source-compact').innerHTML=L.compactSources(['arrow-symbols','symbology','classification']);
    document.querySelector('#styling-checkpoint h2').id='checkpoint-title';
    document.querySelector('#lab-source-root').innerHTML=L.sources(['arrow-symbols','symbology','classification','vector-styling']);document.querySelector('#lab-preview').addEventListener('change',preview);document.querySelector('#preview-reset').addEventListener('click',()=>{document.querySelector('#preview-good').checked=true;preview();});preview();
  }
  root.CARTO_STYLING_RENDER={marker,linePath};
  start();
})(window);
