(function(root){
  'use strict';
  const D=root.CARTO_TOPOLOGY,E=root.CARTO_TOPOLOGY_ENGINE,S=root.CARTO_TOPOLOGY_SCENE,L=root.CARTO_LAB,{esc}=L,controllers=new Map(),sources=['topology-checker','geometry-checker'];
  function draw(d,s,id){
    if(d.id==='T0'){const scene=D.introduction(s.scene,s.state,s.issue),check=E.introductionCheck(scene);return {svg:S.frame(id,d.title,scene.required+' '+check.message,scene.features,check.errors,{labels:s.scene!=='line',terminals:scene.terminals}),status:check.message,dynamic:`<p><strong>${esc(scene.required)}</strong></p><p>${s.scene==='line'?'Pătratele marchează terminale permise. Numai conexiunea internă cerută este verificată.':s.scene==='polygon'?'Gap-ul sau overlap-ul este semnalat deoarece acest model cere acoperire continuă și exclusivă.':'Relația dorită este Within; un punct în exterior nu o respectă.'}</p>`,legend:[{label:s.scene==='line'?'Layer A · rețea; pătrate = terminale permise':'Layer A · contur continuu; Layer B · contur întrerupt / pattern'}]};}
    if(d.id==='T1'){const round=D.rounds[Number(s.round)],check=E.evaluateRound(round,s.perspective,s.answer);return {svg:S.frame(id,round.title,'Perspectiva '+s.perspective+'. '+(round.question||'Alege relația mai specifică dintre A și B.'),round.features),status:check.message,dynamic:`<p><strong>Runda ${Number(s.round)+1} / ${D.rounds.length}.</strong> ${esc(round.question||'Alege relația mai specifică pentru perspectiva selectată.')}</p>${s.answer?`<p>Relația urmărită: <strong>${s.perspective} ${check.relation} ${s.perspective==='A'?'B':'A'}</strong>.</p>`:''}`,legend:[{label:'Layer A · contur continuu; Layer B · contur întrerupt / pattern'}]};}
    const validity=E.polygonValidity(D.validity),relation=E.relations(...D.ruleFeatures),geometry=S.frame(id+'-geometry','Geometry problem',validity.message,[D.validity],s.geometryError?[{type:'self-intersection',location:validity.location}]:[],{labels:false}),topology=S.frame(id+'-topology','Topology rule problem','Geometrii valide individual; relație incompatibilă cu Must not overlap.',D.ruleFeatures,s.topologyError?[{type:'overlap',location:E.ring(relation.location)}]:[]);
    return {svg:`<div class="topology-comparison" data-split="${s.compare}"><section data-pane="geometry"><h4>Geometry problem</h4>${geometry}<p><strong>! Geometrie invalidă</strong></p><p>Self-intersection în același inel. Problema este în construcția geometriei.</p></section><section data-pane="topology"><h4>Topology rule problem</h4>${topology}<p><strong>✓ Geometrii valide individual</strong></p><p>! Relație incompatibilă cu regula <strong>Must not overlap</strong> a acestui model. Suprafața comună aparține ambelor poligoane.</p></section></div>`,status:s.compare?'Compară: geometrie invalidă vs geometrii valide cu overlap interzis de model.':s.pane==='geometry'?'! Geometrie invalidă: self-intersection.':'✓ Geometrii valide individual; ! Semnalat de regula Must not overlap.',dynamic:'<p><strong>Geometry validity</strong> întreabă cum este construită o geometrie. O <strong>regulă topologică</strong> întreabă dacă relația cu alte obiecte respectă modelul. Arată problema evidențiază locația; nu schimbă coordonatele.</p>',legend:[{label:'A și B: contururi diferite; × = intersecție proprie; hașură încrucișată = suprafață comună'}]};
  }
  function afterRender(s,result,card){card.dataset.pane=s.pane||'';card.dataset.compare=String(s.compare);if(card.id!=='T1')return;const round=D.rounds[Number(s.round)],host=card.querySelector('.topology-answers'),key=round.answers.join('|');if(host.dataset.options!==key){host.innerHTML=`<legend>${esc(round.question||'Ce relație este? Alege relația mai specifică.')}</legend><div class="topology-answer-grid">${round.answers.map(answer=>`<label><input type="radio" name="T1-answer" data-answer value="${answer}"><span>${answer}</span></label>`).join('')}</div>`;host.dataset.options=key;}
    host.querySelectorAll('input').forEach(n=>n.checked=n.value===s.answer);const next=card.querySelector('[data-next-round]');next.disabled=Number(s.round)===D.rounds.length-1;next.textContent=next.disabled?'Ultimul exemplu · poți relua':'Următorul exemplu →';
  }
  function start(){document.getElementById('topology-root').innerHTML=D.demos.map(L.shell).join('');for(const d of D.demos){const card=document.getElementById(d.id);card.classList.add('topology-demo');if(d.id==='T1'){card.querySelector('.lab-extra').innerHTML='<fieldset class="topology-answers"></fieldset><button type="button" class="outline-button" data-next-round>Următorul exemplu →</button>';const status=card.querySelector('.lab-status');card.querySelector('.lab-extra').append(status);status.classList.add('topology-feedback');}
      if(d.id==='T2'){card.querySelector('.lab-qgis>a').remove();card.querySelector('.lab-qgis').insertAdjacentHTML('beforeend',`<nav aria-label="Instrumente QGIS pentru T2">${L.sourceLink('geometry-checker')}${L.sourceLink('topology-checker')}</nav>`);}
      controllers.set(d.id,L.mountDemo(d,card,{draw,afterRender,onChange:(s,key)=>{if(d.id==='T1'&&['round','perspective'].includes(key))s.answer='';},compareMode:d.id==='T2'?'toggle':'second'}));
    }
    const card=document.getElementById('T1');card.after(document.getElementById('topology-symmetry'));card.addEventListener('change',event=>{if(event.target.hasAttribute('data-answer'))controllers.get('T1').setState({answer:event.target.value});});card.addEventListener('click',event=>{if(event.target.closest('[data-next-round]')){const c=controllers.get('T1'),s=c.getState();if(Number(s.round)<D.rounds.length-1)c.setState({round:String(Number(s.round)+1),perspective:'A',answer:''});}});
    document.getElementById('topology-source-compact').innerHTML=L.compactSources(sources,{target:'topology-qgis-sources',subject:'topologie'});document.getElementById('topology-source-root').innerHTML=L.sources(sources,{id:'topology-qgis-sources',title:'Topologie · QGIS · Surse oficiale'});
    root.CARTO_TOPOLOGY_CONTROLLERS=controllers;root.CARTO_TOPOLOGY_RENDER={draw,afterRender};const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target)requestAnimationFrame(()=>target.scrollIntoView({block:'start',behavior:'instant'}));
  }
  start();
})(window);
