(function(root){
  'use strict';
  const D=root.CARTO_TRANSPARENCY,L=root.CARTO_LAB,{esc}=L,controllers=new Map();
  const opacity=s=>Number(s.opacity)/100;
  function frame(id,title,description,content){return `<svg viewBox="0 0 480 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="${id}-svg-title ${id}-svg-desc"><title id="${id}-svg-title">${esc(title)}</title><desc id="${id}-svg-desc">${esc(description)}</desc><rect width="480" height="300" fill="${D.background}"/>${content}</svg>`;}
  function background(context=false){return '<g data-context><path d="M30 50H450M30 100H450M30 150H450M30 200H450M30 250H450M80 30V275M160 30V275M240 30V275M320 30V275M400 30V275" stroke="#c8d1cf" stroke-width="1" fill="none"/>'+(context?'<path d="M30 230L440 70M30 90L445 195" stroke="#6b7d80" stroke-width="7" fill="none"/><path d="M35 255V40H440V255Z" stroke="#6b7d80" stroke-width="2" stroke-dasharray="6 4" fill="none"/><circle cx="180" cy="180" r="9" fill="#233f50"/><circle cx="300" cy="125" r="9" fill="#233f50"/>':'')+'</g>';}
  function symbol(feature,{fill=D.fill,fillAlpha=1,strokeAlpha=1,width=8,marker=false}={}){return `<g data-feature="${feature.id}"><rect data-component="fill-outline" x="${feature.x}" y="${feature.y}" width="${feature.width}" height="${feature.height}" fill="${fill}" fill-opacity="${fillAlpha}" stroke="${D.outline}" stroke-opacity="${strokeAlpha}" stroke-width="${width}"/>${marker?`<circle data-component="marker" cx="${feature.x+feature.width/2}" cy="${feature.y+feature.height/2}" r="12" fill="${D.outline}" fill-opacity="${strokeAlpha}"/>`:''}</g>`;}
  function annotations(){return '<g class="opacity-annotations"><path d="M200 120H305V220H200Z" fill="none" stroke="#233f50" stroke-width="2" stroke-dasharray="5 4"/><text x="120" y="39" text-anchor="middle">A numai</text><text x="253" y="39" text-anchor="middle">A ∩ B</text><text x="385" y="39" text-anchor="middle">B numai</text><path d="M120 45V65M253 45V111M385 45V111" stroke="#233f50" stroke-width="1.5" fill="none"/><text x="46" y="285">Contur punctat: zona comună A ∩ B</text></g>';}
  function sameLayer(mode,alpha,order='A'){const features=order==='A'?[D.layer.features[1],D.layer.features[0]]:D.layer.features;
    const objects=features.map(f=>symbol(f,{fillAlpha:mode==='layer'?1:alpha,strokeAlpha:mode==='symbol'?alpha:1})).join('');
    return `<g data-layer="${D.layer.id}" data-composition="${mode}" opacity="${mode==='layer'?alpha:1}">${objects}</g>`;
  }
  function pairScene(id,mode,s){return frame(id,D.modeNames[mode],`Un strat Zone demonstrative, două obiecte A și B. ${D.modeNames[mode]}, ${s.opacity}%. A ∩ B este indicată cu contur punctat.`,background()+sameLayer(mode,opacity(s),s.order)+annotations());}
  const explanation={layer:'Obiectele A și B sunt compuse întâi în strat. Opacitatea se aplică rezultatului comun; umplerile nu se acumulează separat în A ∩ B. Contururile devin și ele transparente.',symbol:'Fiecare obiect este desenat cu componente semi-transparente. În A ∩ B se acumulează contribuțiile umplerilor; opacitatea afectează și contururile.',fill:'Numai culoarea umplerii are alpha redus. În A ∩ B umplerile se compun, dar contururile rămân 100% opace.'};
  function flow(steps){return `<ol class="opacity-flow" aria-label="Ordinea compoziției">${steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`;}
  function layerFlow(mode,p){return mode==='layer'?flow(['Features A + B opace','Compune stratul','Layer opacity '+p+'%','Hartă']):mode==='symbol'?flow(['Simbol A '+p+'% și simbol B '+p+'%','Compune contribuțiile','Hartă']):flow(['Fill color '+p+'%; contur 100%','Compune obiectele','Hartă']);}
  function panels(items){return `<div class="opacity-comparison">${items.map(([title,svg,description])=>`<section><h4>${esc(title)}</h4>${svg}<p>${esc(description)}</p></section>`).join('')}</div>`;}
  function groupComposition(mode,alpha){const objects=D.layer.features.map((f,i)=>`<g data-child-layer="${f.id}" opacity="${mode==='children'?alpha:1}">${symbol(f,{fill:i?D.second:D.fill})}</g>`).join('');return `<g data-group="demonstration-group" opacity="${mode==='group'?alpha:1}">${objects}</g>`;}
  function groupScene(id,mode,s){return frame(id,mode==='group'?'Grup transparent':'Copii transparenți',`Layer B deasupra lui Layer A. ${mode==='group'?'Copii opaci, compune grupul, apoi':'Fiecare strat copil la'} ${s.opacity}%.`,background()+groupComposition(mode,opacity(s))+annotations());}
  function groupFlow(mode,p){return mode==='group'?flow(['Layer A 100% + Layer B 100%','Compune grupul','Group opacity '+p+'%','Hartă']):flow(['Layer A '+p+'% + Layer B '+p+'%','Compune pe hartă']);}
  function draw(d,s,id){let content='',dynamic='',svg='',status=`${s.opacity}%`;const p=opacity(s);
    if(d.id==='T0'||d.id==='T5'){content=background(true)+`<g data-layer="theme" opacity="${p}">${symbol({id:'theme',x:80,y:65,width:310,height:170})}</g>`;
      status=s.opacity===0?'0% · tema invizibilă':s.opacity===100?'100% · opac':`${s.opacity}% · tema și fundalul sunt vizibile simultan`;
      dynamic=d.id==='T5'?`<p>${s.opacity===100?'Contextul din interior este ascuns.':s.opacity<30?'Tema este discretă și poate pierde dominanța.':'Tema și contextul pot fi citite simultan; apreciază contrastul în scenă.'} Procentele nu exprimă o valoare din date.</p>`:`<p>${s.opacity===0?'Obiectul există în continuare în date, chiar dacă nu îl vezi.':'Opacitatea schimbă numai desenul obiectului.'}</p>`;
    }else if(d.id==='T1'){const isOpacity=s.concept==='opacity';content=`<g class="opacity-concept"><rect x="50" y="55" width="380" height="180" fill="#fff" stroke="#233f50"/><text x="240" y="119" text-anchor="middle">${isOpacity?'OPACITY':'BLEND MODE'}</text><text x="240" y="157" text-anchor="middle">${isOpacity?'CÂT se vede':'CUM se combină'}</text><text x="240" y="202" text-anchor="middle" class="opacity-note">${isOpacity?'0% → 50% → 100%':'Explicație conceptuală · etapa următoare'}</text></g>`;status=isOpacity?'Cantitatea vizibilă':'Mod de combinare · doar concept';dynamic='<p>Nu schimbăm algoritmul de combinare în acest laborator. Transparența nu este NoData și nu execută Union, Dissolve sau alte operații de analiză.</p>';
    }else if(d.id==='T2'){svg=pairScene(id,s.mode,s);status=`${D.modeNames[s.mode]} · ${s.opacity}% · ${s.order} deasupra · un strat, două obiecte`;dynamic=`<p><strong>Privește zona A ∩ B.</strong> ${esc(explanation[s.mode])}</p>${layerFlow(s.mode,s.opacity)}<p>Cu aceeași culoare, unele umpleri pot arăta identic după inversare. Conturul interior arată care obiect este desenat ultimul. Geometria nu se schimbă.</p>`;
    }else if(d.id==='T3'){content=background()+symbol({id:'single',x:80,y:75,width:320,height:160},{fillAlpha:p,strokeAlpha:s.mode==='symbol'?p:1,width:16,marker:true});status=`${s.mode==='symbol'?'Symbol opacity':'Fill color alpha'} · ${s.opacity}%`;dynamic='<p>'+esc(s.mode==='symbol'?'Umplerea, conturul și markerul au opacitatea redusă.':'Umplerea este transparentă; conturul și markerul rămân complet opace.')+'</p>';
    }else if(d.id==='T4'){const features=s.order==='A'?[D.layer.features[1],D.layer.features[0]]:D.layer.features;content=background()+features.map(f=>`<g data-distinct-layer="${f.id}" opacity="${p}">${symbol(f,{fill:f.id==='A'?D.fill:D.second})}</g>`).join('')+annotations();status=`${s.order==='A'?'Tema':'Contextul'} deasupra · ambele straturi ${s.opacity}%`;dynamic=flow([s.order==='A'?'Contextul → Tema':'Tema → Contextul','Hartă'])+'<p>Spre deosebire de T2, acestea sunt două straturi distincte. Datele și opacitățile rămân neschimbate.</p>';
    }else if(d.id==='T6'){svg=groupScene(id,s.mode,s);status=s.mode==='children'?`Layer A ${s.opacity}% + Layer B ${s.opacity}%`:`Layer A 100% + Layer B 100% → Group ${s.opacity}%`;dynamic=groupFlow(s.mode,s.opacity)+'<p>Layer B este deasupra. În grupul compus, părțile lui Layer A acoperite de B rămân acoperite, chiar când grupul devine transparent.</p>';
    }else if(d.id==='T7'){content=[['Original',D.background,1],['Fundal deschis','#ffffff',p],['Fundal închis','#344c59',p]].map(([title,bg,alpha],i)=>`<g transform="translate(${i*155+10} 0)"><rect x="0" y="45" width="140" height="190" fill="${bg}"/><g opacity="${alpha}">${symbol({id:'swatch-'+i,x:25,y:80,width:90,height:95})}</g><text x="70" y="260" text-anchor="middle" class="opacity-note">${title}</text><text x="70" y="285" text-anchor="middle" class="opacity-note">${i?s.opacity:100}%</text></g>`).join('');status=`Original 100% · pe hartă ${s.opacity}% · două fundaluri`;dynamic='<p>Aceeași culoare de bază, două aparențe rezultate. Fundalurile sunt alese explicit și rămân identice în ambele teme UI.</p>';}
    return {svg:svg||frame(id,d.title,status,content),status,dynamic,legend:[{label:d.id==='T2'?'Un strat · Zone demonstrative · A și B':'Geometrii și atribute sintetice, neschimbate',color:D.fill}]};
  }
  function afterRender(s,result,card){const d=D.demos.find(d=>d.id===card.id),compare=card.querySelector('.lab-compare');
    if(d.id==='T2'||d.id==='T6'){compare.hidden=!s.compare;
      if(s.compare)compare.innerHTML=d.id==='T2'?panels(['layer','symbol','fill'].map(mode=>[D.modeNames[mode]+' · '+s.opacity+'%',pairScene(d.id+'-compare-'+mode,mode,s),explanation[mode]])):panels(['children','group'].map(mode=>[mode==='children'?'Fiecare copil '+s.opacity+'%':'Grupul '+s.opacity+'%',groupScene(d.id+'-compare-'+mode,mode,s),mode==='children'?'Fiecare copil contribuie separat.':'Copii opaci → compune grupul → opacitate.']));
      compare.classList.toggle('opacity-compare-two',d.id==='T6');
    }
    if(d.id==='T2'){card.querySelector('.lab-controls label[for="T2-opacity"]').firstChild.textContent=({layer:'Layer opacity ',symbol:'Feature / symbol opacity ',fill:'Fill color opacity '})[s.mode];}
    if(['T2','T3'].includes(d.id)){card.querySelector('.qgis-path').textContent=D.paths[s.mode];card.querySelector('.lab-qgis>a').outerHTML=L.sourceLink({layer:'vector-layer-rendering',symbol:'symbol-opacity',fill:'color-opacity'}[s.mode]);}
    if(d.id==='T5'){card.querySelector('.lab-extra').innerHTML='<fieldset class="opacity-presets"><legend>Valori de explorat</legend>'+[100,75,50,25].map(value=>`<button type="button" class="outline-button" data-opacity-preset="${value}" aria-pressed="${s.opacity===value}">${value}%</button>`).join('')+'</fieldset>';}
    // On phones the main scene and native selector stay large; comparisons retain text and controls.
    if(d.id==='T2'&&s.compare)card.querySelector('.lab-compare').insertAdjacentHTML('beforeend','<p class="opacity-mobile-compare-note">Pe mobil, folosește selectorul de mai sus pentru a compara cele trei niveluri în scena mare, la aceeași valoare.</p>');
  }
  function start(){const host=document.getElementById('transparency-root');if(!host)return;host.innerHTML=D.demos.map(L.shell).join('');
    D.demos.forEach(d=>{const card=document.getElementById(d.id);if(['T2','T6'].includes(d.id))card.querySelector('.lab-demo-layout').after(card.querySelector('.lab-compare'));controllers.set(d.id,L.mountDemo(d,card,{draw,afterRender,alternate:s=>{if(d.id==='T5')s.opacity=s.opacity===100?50:100;return s;}}));if(d.id==='T2')card.querySelector('.lab-qgis').insertAdjacentHTML('beforeend','<p class="qgis-path">Ordinea obiectelor: Layer Properties → Symbology → Layer rendering → Control feature rendering order.</p>');if(d.id==='T5')card.addEventListener('click',e=>{const button=e.target.closest('[data-opacity-preset]');if(button){controllers.get(d.id).setState({opacity:Number(button.dataset.opacityPreset)});card.querySelector(`[data-opacity-preset="${button.dataset.opacityPreset}"]`).focus();}});});
    L.checkpoint(document.getElementById('transparency-checkpoint'),D.quiz,{title:'Checkpoint · Transparență',id:'transparency-checkpoint-title',namespace:'transparency-quiz'});
    const sources=['vector-layer-rendering','symbol-opacity','color-opacity','group-rendering'];document.getElementById('opacity-source-compact').innerHTML=L.compactSources(sources,{target:'opacity-qgis-sources',subject:'transparență și compoziție'});document.getElementById('opacity-source-root').innerHTML=L.sources(sources,{id:'opacity-qgis-sources',title:'Aplică transparența în QGIS'});
    function reveal(){const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target)requestAnimationFrame(()=>target.scrollIntoView({block:'start',behavior:'instant'}));}addEventListener('hashchange',reveal);reveal();
  }
  root.CARTO_OPACITY_RENDER={draw,sameLayer,groupComposition};start();
})(window);
